// Code generated by MockGen. DO NOT EDIT.
// Source: core/context.go
//
// Generated by this command:
//
//	mockgen -source=core/context.go -destination=test/mock_context.go -package=test
//

// Package test is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockContext) GetHistory() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockContextMockRecorder) GetHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockContext)(nil).GetHistory))
}

// GetKnowledgeBase mocks base method.
func (m *MockContext) GetKnowledgeBase() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockContextMockRecorder) GetKnowledgeBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockContext)(nil).GetKnowledgeBase))
}

// GetModelProviders mocks base method.
func (m *MockContext) GetModelProviders() []core.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProviders")
	ret0, _ := ret[0].([]core.Provider)
	return ret0
}

// GetModelProviders indicates an expected call of GetModelProviders.
func (mr *MockContextMockRecorder) GetModelProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProviders", reflect.TypeOf((*MockContext)(nil).GetModelProviders))
}

// GetPrompt mocks base method.
func (m *MockContext) GetPrompt() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockContextMockRecorder) GetPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockContext)(nil).GetPrompt))
}

// GetSessionConfig mocks base method.
func (m *MockContext) GetSessionConfig() core.SessionConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionConfig")
	ret0, _ := ret[0].(core.SessionConfig)
	return ret0
}

// GetSessionConfig indicates an expected call of GetSessionConfig.
func (mr *MockContextMockRecorder) GetSessionConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionConfig", reflect.TypeOf((*MockContext)(nil).GetSessionConfig))
}

// GetSkills mocks base method.
func (m *MockContext) GetSkills() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkills")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetSkills indicates an expected call of GetSkills.
func (mr *MockContextMockRecorder) GetSkills() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkills", reflect.TypeOf((*MockContext)(nil).GetSkills))
}

// GetToolsConfig mocks base method.
func (m *MockContext) GetToolsConfig() []core.ToolConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolsConfig")
	ret0, _ := ret[0].([]core.ToolConfig)
	return ret0
}

// GetToolsConfig indicates an expected call of GetToolsConfig.
func (mr *MockContextMockRecorder) GetToolsConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolsConfig", reflect.TypeOf((*MockContext)(nil).GetToolsConfig))
}

// LoadConfigs mocks base method.
// auto-generated: updated to match new LoadConfigs() signature
func (m *MockContext) LoadConfigs() core.AgentCoreConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigs")
	ret0, _ := ret[0].(core.AgentCoreConfig)
	return ret0
}

// LoadConfigs indicates an expected call of LoadConfigs.
// auto-generated: updated to match new LoadConfigs() signature
func (mr *MockContextMockRecorder) LoadConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigs", reflect.TypeOf((*MockContext)(nil).LoadConfigs))
}

// SetHistory mocks base method.
func (m *MockContext) SetHistory(arg0 core.HistoryConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockContextMockRecorder) SetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockContext)(nil).SetHistory), arg0)
}

// SetKnowledgeBase mocks base method.
func (m *MockContext) SetKnowledgeBase(arg0 core.KnowledgeBaseConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKnowledgeBase", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetKnowledgeBase indicates an expected call of SetKnowledgeBase.
func (mr *MockContextMockRecorder) SetKnowledgeBase(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKnowledgeBase", reflect.TypeOf((*MockContext)(nil).SetKnowledgeBase), arg0)
}

// SetLanguage mocks base method.
func (m *MockContext) SetLanguage(arg0 core.LanguageType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLanguage", arg0)
}

// SetLanguage indicates an expected call of SetLanguage.
func (mr *MockContextMockRecorder) SetLanguage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLanguage", reflect.TypeOf((*MockContext)(nil).SetLanguage), arg0)
}

// SetLogger mocks base method.
func (m *MockContext) SetLogger(arg0 core.AgentConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogger", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockContextMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockContext)(nil).SetLogger), arg0)
}

// SetProviders mocks base method.
func (m *MockContext) SetProviders(arg0 []core.Provider) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviders", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetProviders indicates an expected call of SetProviders.
func (mr *MockContextMockRecorder) SetProviders(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviders", reflect.TypeOf((*MockContext)(nil).SetProviders), arg0)
}

// SetPrompt mocks base method.
func (m *MockContext) SetPrompt(arg0 core.PromptConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrompt", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetPrompt indicates an expected call of SetPrompt.
func (mr *MockContextMockRecorder) SetPrompt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrompt", reflect.TypeOf((*MockContext)(nil).SetPrompt), arg0)
}

// SetSkills mocks base method.
func (m *MockContext) SetSkills(arg0 core.SkillConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSkills", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetSkills indicates an expected call of SetSkills.
func (mr *MockContextMockRecorder) SetSkills(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSkills", reflect.TypeOf((*MockContext)(nil).SetSkills), arg0)
}

// SetToolsConfig mocks base method.
func (m *MockContext) SetToolsConfig(arg0 []core.ToolConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetToolsConfig", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetToolsConfig indicates an expected call of SetToolsConfig.
func (mr *MockContextMockRecorder) SetToolsConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToolsConfig", reflect.TypeOf((*MockContext)(nil).SetToolsConfig), arg0)
}

// MockSessionContext is a mock of SessionContext interface.
type MockSessionContext struct {
	ctrl     *gomock.Controller
	recorder *MockSessionContextMockRecorder
	isgomock struct{}
}

// MockSessionContextMockRecorder is the mock recorder for MockSessionContext.
type MockSessionContextMockRecorder struct {
	mock *MockSessionContext
}

// NewMockSessionContext creates a new mock instance.
func NewMockSessionContext(ctrl *gomock.Controller) *MockSessionContext {
	mock := &MockSessionContext{ctrl: ctrl}
	mock.recorder = &MockSessionContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionContext) EXPECT() *MockSessionContextMockRecorder {
	return m.recorder
}

// GenerateFinalContext mocks base method.
func (m *MockSessionContext) GenerateFinalContext(query core.Question) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFinalContext", query)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateFinalContext indicates an expected call of GenerateFinalContext.
func (mr *MockSessionContextMockRecorder) GenerateFinalContext(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFinalContext", reflect.TypeOf((*MockSessionContext)(nil).GenerateFinalContext), query)
}
