// Code generated by MockGen. DO NOT EDIT.
// Source: core/i18n.go
//
// Generated by this command:
//
//	mockgen -source=core/i18n.go -destination=test/mock/mock_i18n.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockI18n is a mock of I18n interface.
type MockI18n struct {
	ctrl     *gomock.Controller
	recorder *MockI18nMockRecorder
	isgomock struct{}
}

// MockI18nMockRecorder is the mock recorder for MockI18n.
type MockI18nMockRecorder struct {
	mock *MockI18n
}

// NewMockI18n creates a new mock instance.
func NewMockI18n(ctrl *gomock.Controller) *MockI18n {
	mock := &MockI18n{ctrl: ctrl}
	mock.recorder = &MockI18nMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockI18n) EXPECT() *MockI18nMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockI18n) Translate(key core.MessageCode, targetLanguage core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", key, targetLanguage)
	ret0, _ := ret[0].(string)
	return ret0
}

// Translate indicates an expected call of Translate.
func (mr *MockI18nMockRecorder) Translate(key, targetLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockI18n)(nil).Translate), key, targetLanguage)
}
