// Code generated by MockGen. DO NOT EDIT.
// Source: core/provider.go
//
// Generated by this command:
//
//	mockgen -source=core/provider.go -destination=test/mock/mock_provider.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockProvider) Auth(arg0 core.ModelConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockProviderMockRecorder) Auth(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockProvider)(nil).Auth), arg0)
}

// Complete mocks base method.
func (m *MockProvider) Complete(messages []core.ReActMessage, tools []core.Tool) (core.Answer, []core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", messages, tools)
	ret0, _ := ret[0].(core.Answer)
	ret1, _ := ret[1].([]core.Diagnostic)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockProviderMockRecorder) Complete(messages, tools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockProvider)(nil).Complete), messages, tools)
}

// CompleteStream mocks base method.
func (m *MockProvider) CompleteStream(messages []core.ReActMessage, tools []core.Tool) (<-chan core.Answer, []core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteStream", messages, tools)
	ret0, _ := ret[0].(<-chan core.Answer)
	ret1, _ := ret[1].([]core.Diagnostic)
	return ret0, ret1
}

// CompleteStream indicates an expected call of CompleteStream.
func (mr *MockProviderMockRecorder) CompleteStream(messages, tools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteStream", reflect.TypeOf((*MockProvider)(nil).CompleteStream), messages, tools)
}

// GetID mocks base method.
func (m *MockProvider) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockProviderMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockProvider)(nil).GetID))
}

// GetModelConfig mocks base method.
func (m *MockProvider) GetModelConfig() core.ModelConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelConfig")
	ret0, _ := ret[0].(core.ModelConfig)
	return ret0
}

// GetModelConfig indicates an expected call of GetModelConfig.
func (mr *MockProviderMockRecorder) GetModelConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelConfig", reflect.TypeOf((*MockProvider)(nil).GetModelConfig))
}

// GetName mocks base method.
func (m *MockProvider) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockProviderMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockProvider)(nil).GetName))
}

// Init mocks base method.
func (m *MockProvider) Init(arg0 core.ModelConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockProviderMockRecorder) Init(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockProvider)(nil).Init), arg0)
}
