// Code generated by MockGen. DO NOT EDIT.
// Source: core/kb.go
//
// Generated by this command:
//
//	mockgen -source=core/kb.go -destination=test/mock_kb.go -package=test
//

// Package test is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockKnowledgeBaseManger is a mock of KnowledgeBaseManger interface.
type MockKnowledgeBaseManger struct {
	ctrl     *gomock.Controller
	recorder *MockKnowledgeBaseMangerMockRecorder
	isgomock struct{}
}

// MockKnowledgeBaseMangerMockRecorder is the mock recorder for MockKnowledgeBaseManger.
type MockKnowledgeBaseMangerMockRecorder struct {
	mock *MockKnowledgeBaseManger
}

// NewMockKnowledgeBaseManger creates a new mock instance.
func NewMockKnowledgeBaseManger(ctrl *gomock.Controller) *MockKnowledgeBaseManger {
	mock := &MockKnowledgeBaseManger{ctrl: ctrl}
	mock.recorder = &MockKnowledgeBaseMangerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKnowledgeBaseManger) EXPECT() *MockKnowledgeBaseMangerMockRecorder {
	return m.recorder
}

// DeleteKnowledgebase mocks base method.
func (m *MockKnowledgeBaseManger) DeleteKnowledgebase(data any) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKnowledgebase", data)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// DeleteKnowledgebase indicates an expected call of DeleteKnowledgebase.
func (mr *MockKnowledgeBaseMangerMockRecorder) DeleteKnowledgebase(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKnowledgebase", reflect.TypeOf((*MockKnowledgeBaseManger)(nil).DeleteKnowledgebase), data)
}

// InsertKnowledgebase mocks base method.
func (m *MockKnowledgeBaseManger) InsertKnowledgebase(data any) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertKnowledgebase", data)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// InsertKnowledgebase indicates an expected call of InsertKnowledgebase.
func (mr *MockKnowledgeBaseMangerMockRecorder) InsertKnowledgebase(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertKnowledgebase", reflect.TypeOf((*MockKnowledgeBaseManger)(nil).InsertKnowledgebase), data)
}

// SearchKnowledgebase mocks base method.
func (m *MockKnowledgeBaseManger) SearchKnowledgebase(keyword string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchKnowledgebase", keyword)
	ret0, _ := ret[0].(string)
	return ret0
}

// SearchKnowledgebase indicates an expected call of SearchKnowledgebase.
func (mr *MockKnowledgeBaseMangerMockRecorder) SearchKnowledgebase(keyword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchKnowledgebase", reflect.TypeOf((*MockKnowledgeBaseManger)(nil).SearchKnowledgebase), keyword)
}

// SetStorage mocks base method.
func (m *MockKnowledgeBaseManger) SetStorage(storage core.Storage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStorage", storage)
}

// SetStorage indicates an expected call of SetStorage.
func (mr *MockKnowledgeBaseMangerMockRecorder) SetStorage(storage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStorage", reflect.TypeOf((*MockKnowledgeBaseManger)(nil).SetStorage), storage)
}

// UpdateKnowledgebase mocks base method.
func (m *MockKnowledgeBaseManger) UpdateKnowledgebase(data any) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnowledgebase", data)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// UpdateKnowledgebase indicates an expected call of UpdateKnowledgebase.
func (mr *MockKnowledgeBaseMangerMockRecorder) UpdateKnowledgebase(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnowledgebase", reflect.TypeOf((*MockKnowledgeBaseManger)(nil).UpdateKnowledgebase), data)
}
