// Code generated by MockGen. DO NOT EDIT.
// Source: core/errcode.go
//
// Generated by this command:
//
//	mockgen -source=core/errcode.go -destination=test/mock_errcode.go -package=test
//

// Package test is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSerializable is a mock of Serializable interface.
type MockSerializable struct {
	ctrl     *gomock.Controller
	recorder *MockSerializableMockRecorder
	isgomock struct{}
}

// MockSerializableMockRecorder is the mock recorder for MockSerializable.
type MockSerializableMockRecorder struct {
	mock *MockSerializable
}

// NewMockSerializable creates a new mock instance.
func NewMockSerializable(ctrl *gomock.Controller) *MockSerializable {
	mock := &MockSerializable{ctrl: ctrl}
	mock.recorder = &MockSerializableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSerializable) EXPECT() *MockSerializableMockRecorder {
	return m.recorder
}

// ToString mocks base method.
func (m *MockSerializable) ToString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockSerializableMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockSerializable)(nil).ToString))
}
