// Code generated by MockGen. DO NOT EDIT.
// Source: core/context.go
//
// Generated by this command:
//
//	mockgen -source=core/context.go -destination=test/mock/mock_context.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockContext) GetHistory() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockContextMockRecorder) GetHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockContext)(nil).GetHistory))
}

// GetKnowledgeBase mocks base method.
func (m *MockContext) GetKnowledgeBase() []core.KnowledgeBase[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase")
	ret0, _ := ret[0].([]core.KnowledgeBase[any])
	return ret0
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockContextMockRecorder) GetKnowledgeBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockContext)(nil).GetKnowledgeBase))
}

// GetModelProviders mocks base method.
func (m *MockContext) GetModelProviders() []core.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProviders")
	ret0, _ := ret[0].([]core.Provider)
	return ret0
}

// GetModelProviders indicates an expected call of GetModelProviders.
func (mr *MockContextMockRecorder) GetModelProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProviders", reflect.TypeOf((*MockContext)(nil).GetModelProviders))
}

// GetPrompt mocks base method.
func (m *MockContext) GetPrompt() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockContextMockRecorder) GetPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockContext)(nil).GetPrompt))
}

// GetToolsConfig mocks base method.
func (m *MockContext) GetToolsConfig() []core.ToolConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolsConfig")
	ret0, _ := ret[0].([]core.ToolConfig)
	return ret0
}

// GetToolsConfig indicates an expected call of GetToolsConfig.
func (mr *MockContextMockRecorder) GetToolsConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolsConfig", reflect.TypeOf((*MockContext)(nil).GetToolsConfig))
}

// SetHistory mocks base method.
func (m *MockContext) SetHistory(arg0 core.HistoryConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockContextMockRecorder) SetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockContext)(nil).SetHistory), arg0)
}

// SetKnowledgeBase mocks base method.
func (m *MockContext) SetKnowledgeBase(arg0 []core.KnowledgeBaseConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKnowledgeBase", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetKnowledgeBase indicates an expected call of SetKnowledgeBase.
func (mr *MockContextMockRecorder) SetKnowledgeBase(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKnowledgeBase", reflect.TypeOf((*MockContext)(nil).SetKnowledgeBase), arg0)
}

// SetPrompt mocks base method.
func (m *MockContext) SetPrompt(arg0 core.PromptConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrompt", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetPrompt indicates an expected call of SetPrompt.
func (mr *MockContextMockRecorder) SetPrompt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrompt", reflect.TypeOf((*MockContext)(nil).SetPrompt), arg0)
}

// SetProviders mocks base method.
func (m *MockContext) SetProviders(arg0 []core.Provider) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviders", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetProviders indicates an expected call of SetProviders.
func (mr *MockContextMockRecorder) SetProviders(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviders", reflect.TypeOf((*MockContext)(nil).SetProviders), arg0)
}

// SetSkills mocks base method.
func (m *MockContext) SetSkills(arg0 []core.SkillDefinition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSkills", arg0)
}

// SetSkills indicates an expected call of SetSkills.
func (mr *MockContextMockRecorder) SetSkills(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSkills", reflect.TypeOf((*MockContext)(nil).SetSkills), arg0)
}

// GetSkill mocks base method.
func (m *MockContext) GetSkill(arg0 string) *core.SkillDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkill", arg0)
	ret0, _ := ret[0].(*core.SkillDefinition)
	return ret0
}

// GetSkill indicates an expected call of GetSkill.
func (mr *MockContextMockRecorder) GetSkill(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkill", reflect.TypeOf((*MockContext)(nil).GetSkill), arg0)
}

// GetSkills mocks base method.
func (m *MockContext) GetSkills() []core.SkillDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkills")
	ret0, _ := ret[0].([]core.SkillDefinition)
	return ret0
}

// GetSkills indicates an expected call of GetSkills.
func (mr *MockContextMockRecorder) GetSkills() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkills", reflect.TypeOf((*MockContext)(nil).GetSkills))
}

// SetToolsConfig mocks base method.
func (m *MockContext) SetToolsConfig(arg0 []core.ToolConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetToolsConfig", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetToolsConfig indicates an expected call of SetToolsConfig.
func (mr *MockContextMockRecorder) SetToolsConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToolsConfig", reflect.TypeOf((*MockContext)(nil).SetToolsConfig), arg0)
}
