// Code generated by MockGen. DO NOT EDIT.
// Source: core/server.go
//
// Generated by this command:
//
//	mockgen -source=core/server.go -destination=test/mock/mock_server.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	log "log"
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentServer is a mock of AgentServer interface.
type MockAgentServer struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServerMockRecorder
	isgomock struct{}
}

// MockAgentServerMockRecorder is the mock recorder for MockAgentServer.
type MockAgentServerMockRecorder struct {
	mock *MockAgentServer
}

// NewMockAgentServer creates a new mock instance.
func NewMockAgentServer(ctrl *gomock.Controller) *MockAgentServer {
	mock := &MockAgentServer{ctrl: ctrl}
	mock.recorder = &MockAgentServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServer) EXPECT() *MockAgentServerMockRecorder {
	return m.recorder
}

// GetAgentCore mocks base method.
func (m *MockAgentServer) GetAgentCore() core.AgentCore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCore")
	ret0, _ := ret[0].(core.AgentCore)
	return ret0
}

// GetAgentCore indicates an expected call of GetAgentCore.
func (mr *MockAgentServerMockRecorder) GetAgentCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCore", reflect.TypeOf((*MockAgentServer)(nil).GetAgentCore))
}

// GetAppConfig mocks base method.
func (m *MockAgentServer) GetAppConfig() core.AppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppConfig")
	ret0, _ := ret[0].(core.AppConfig)
	return ret0
}

// GetAppConfig indicates an expected call of GetAppConfig.
func (mr *MockAgentServerMockRecorder) GetAppConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppConfig", reflect.TypeOf((*MockAgentServer)(nil).GetAppConfig))
}

// GetLogger mocks base method.
func (m *MockAgentServer) GetLogger() *log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*log.Logger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockAgentServerMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockAgentServer)(nil).GetLogger))
}

// GracefulQuit mocks base method.
func (m *MockAgentServer) GracefulQuit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulQuit")
}

// GracefulQuit indicates an expected call of GracefulQuit.
func (mr *MockAgentServerMockRecorder) GracefulQuit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulQuit", reflect.TypeOf((*MockAgentServer)(nil).GracefulQuit))
}

// SetAgentCore mocks base method.
func (m *MockAgentServer) SetAgentCore(arg0 core.AgentCore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAgentCore", arg0)
}

// SetAgentCore indicates an expected call of SetAgentCore.
func (mr *MockAgentServerMockRecorder) SetAgentCore(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentCore", reflect.TypeOf((*MockAgentServer)(nil).SetAgentCore), arg0)
}

// SetAppConfig mocks base method.
func (m *MockAgentServer) SetAppConfig(arg0 core.AppConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppConfig", arg0)
}

// SetAppConfig indicates an expected call of SetAppConfig.
func (mr *MockAgentServerMockRecorder) SetAppConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppConfig", reflect.TypeOf((*MockAgentServer)(nil).SetAppConfig), arg0)
}

// SetLogger mocks base method.
func (m *MockAgentServer) SetLogger(arg0 *log.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", arg0)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockAgentServerMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockAgentServer)(nil).SetLogger), arg0)
}

// SetRouter mocks base method.
func (m *MockAgentServer) SetRouter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRouter")
}

// SetRouter indicates an expected call of SetRouter.
func (mr *MockAgentServerMockRecorder) SetRouter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRouter", reflect.TypeOf((*MockAgentServer)(nil).SetRouter))
}

// Start mocks base method.
func (m *MockAgentServer) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockAgentServerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAgentServer)(nil).Start))
}

// Stop mocks base method.
func (m *MockAgentServer) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockAgentServerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAgentServer)(nil).Stop))
}
