// Code generated by MockGen. DO NOT EDIT.
// Source: core/harness.go
//
// Generated by this command:
//
//	mockgen -source=core/harness.go -destination=test/mock/mock_harness.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockHarness is a mock of Harness interface.
type MockHarness struct {
	ctrl     *gomock.Controller
	recorder *MockHarnessMockRecorder
	isgomock struct{}
}

// MockHarnessMockRecorder is the mock recorder for MockHarness.
type MockHarnessMockRecorder struct {
	mock *MockHarness
}

// NewMockHarness creates a new mock instance.
func NewMockHarness(ctrl *gomock.Controller) *MockHarness {
	mock := &MockHarness{ctrl: ctrl}
	mock.recorder = &MockHarnessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHarness) EXPECT() *MockHarnessMockRecorder {
	return m.recorder
}

// AddAgentHistory mocks base method.
func (m *MockHarness) AddAgentHistory(agentHistory *[]byte, maxSize int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAgentHistory", agentHistory, maxSize)
}

// AddAgentHistory indicates an expected call of AddAgentHistory.
func (mr *MockHarnessMockRecorder) AddAgentHistory(agentHistory, maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentHistory", reflect.TypeOf((*MockHarness)(nil).AddAgentHistory), agentHistory, maxSize)
}

// AddPrompt mocks base method.
func (m *MockHarness) AddPrompt(systemPrompt *[]byte, document []byte, maxSize int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPrompt", systemPrompt, document, maxSize)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AddPrompt indicates an expected call of AddPrompt.
func (mr *MockHarnessMockRecorder) AddPrompt(systemPrompt, document, maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPrompt", reflect.TypeOf((*MockHarness)(nil).AddPrompt), systemPrompt, document, maxSize)
}

// GenerateFinalPrompt mocks base method.
func (m *MockHarness) GenerateFinalPrompt(context core.Context, maxSize int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFinalPrompt", context, maxSize)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateFinalPrompt indicates an expected call of GenerateFinalPrompt.
func (mr *MockHarnessMockRecorder) GenerateFinalPrompt(context, maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFinalPrompt", reflect.TypeOf((*MockHarness)(nil).GenerateFinalPrompt), context, maxSize)
}

// GenerateToolConfirmResponse mocks base method.
func (m *MockHarness) GenerateToolConfirmResponse(session core.Session, calls []core.ToolConfirmCall, usage core.Usage) core.Answer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToolConfirmResponse", session, calls, usage)
	ret0, _ := ret[0].(core.Answer)
	return ret0
}

// GenerateToolConfirmResponse indicates an expected call of GenerateToolConfirmResponse.
func (mr *MockHarnessMockRecorder) GenerateToolConfirmResponse(session, calls, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToolConfirmResponse", reflect.TypeOf((*MockHarness)(nil).GenerateToolConfirmResponse), session, calls, usage)
}

// GetConfirmDestructiveToolResult mocks base method.
func (m *MockHarness) GetConfirmDestructiveToolResult(toolName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmDestructiveToolResult", toolName)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfirmDestructiveToolResult indicates an expected call of GetConfirmDestructiveToolResult.
func (mr *MockHarnessMockRecorder) GetConfirmDestructiveToolResult(toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmDestructiveToolResult", reflect.TypeOf((*MockHarness)(nil).GetConfirmDestructiveToolResult), toolName)
}

// GetConfirmDestructiveToolAnswer mocks base method.
func (m *MockHarness) GetConfirmDestructiveToolAnswer(toolName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmDestructiveToolAnswer", toolName)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfirmDestructiveToolAnswer indicates an expected call of GetConfirmDestructiveToolAnswer.
func (mr *MockHarnessMockRecorder) GetConfirmDestructiveToolAnswer(toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmDestructiveToolAnswer", reflect.TypeOf((*MockHarness)(nil).GetConfirmDestructiveToolAnswer), toolName)
}

// GetCurrRoundKnowledges mocks base method.
func (m *MockHarness) GetCurrRoundKnowledges(question core.Question) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrRoundKnowledges", question)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrRoundKnowledges indicates an expected call of GetCurrRoundKnowledges.
func (mr *MockHarnessMockRecorder) GetCurrRoundKnowledges(question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrRoundKnowledges", reflect.TypeOf((*MockHarness)(nil).GetCurrRoundKnowledges), question)
}

// GetDefaultAnswer mocks base method.
func (m *MockHarness) GetDefaultAnswer() core.AgentResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultAnswer")
	ret0, _ := ret[0].(core.AgentResponse)
	return ret0
}

// GetDefaultAnswer indicates an expected call of GetDefaultAnswer.
func (mr *MockHarnessMockRecorder) GetDefaultAnswer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultAnswer", reflect.TypeOf((*MockHarness)(nil).GetDefaultAnswer))
}

// GetUserToolConfirmMessage mocks base method.
func (m *MockHarness) GetUserToolConfirmMessage(toolName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserToolConfirmMessage", toolName)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserToolConfirmMessage indicates an expected call of GetUserToolConfirmMessage.
func (mr *MockHarnessMockRecorder) GetUserToolConfirmMessage(toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserToolConfirmMessage", reflect.TypeOf((*MockHarness)(nil).GetUserToolConfirmMessage), toolName)
}

// HandleUserQuestion mocks base method.
func (m *MockHarness) HandleUserQuestion(session core.Session, question core.Question) (*core.ReActMessage, core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUserQuestion", session, question)
	ret0, _ := ret[0].(*core.ReActMessage)
	ret1, _ := ret[1].(core.Diagnostic)
	return ret0, ret1
}

// HandleUserQuestion indicates an expected call of HandleUserQuestion.
func (mr *MockHarnessMockRecorder) HandleUserQuestion(session, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUserQuestion", reflect.TypeOf((*MockHarness)(nil).HandleUserQuestion), session, question)
}

// HandleUserToolConfirm mocks base method.
func (m *MockHarness) HandleUserToolConfirm(session core.Session, question core.Question) []core.ReActMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUserToolConfirm", session, question)
	ret0, _ := ret[0].([]core.ReActMessage)
	return ret0
}

// HandleUserToolConfirm indicates an expected call of HandleUserToolConfirm.
func (mr *MockHarnessMockRecorder) HandleUserToolConfirm(session, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUserToolConfirm", reflect.TypeOf((*MockHarness)(nil).HandleUserToolConfirm), session, question)
}

// IsSessionCancelled mocks base method.
func (m *MockHarness) IsSessionCancelled(session core.Session, toolCalls []core.ToolCall) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSessionCancelled", session, toolCalls)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSessionCancelled indicates an expected call of IsSessionCancelled.
func (mr *MockHarnessMockRecorder) IsSessionCancelled(session, toolCalls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSessionCancelled", reflect.TypeOf((*MockHarness)(nil).IsSessionCancelled), session, toolCalls)
}

// LoadTools mocks base method.
func (m *MockHarness) LoadTools(skillName string, session core.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LoadTools", skillName, session)
}

// LoadTools indicates an expected call of LoadTools.
func (mr *MockHarnessMockRecorder) LoadTools(skillName, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTools", reflect.TypeOf((*MockHarness)(nil).LoadTools), skillName, session)
}

// RunSubSession mocks base method.
func (m *MockHarness) RunSubSession(session core.Session, args map[string]any, model string) (string, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSubSession", session, args, model)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// RunSubSession indicates an expected call of RunSubSession.
func (mr *MockHarnessMockRecorder) RunSubSession(session, args, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSubSession", reflect.TypeOf((*MockHarness)(nil).RunSubSession), session, args, model)
}

// RunToolCall mocks base method.
func (m *MockHarness) RunToolCall(session core.Session, toolCall core.ToolCall, targetTool core.Tool, args map[string]any, model string) (string, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunToolCall", session, toolCall, targetTool, args, model)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// RunToolCall indicates an expected call of RunToolCall.
func (mr *MockHarnessMockRecorder) RunToolCall(session, toolCall, targetTool, args, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunToolCall", reflect.TypeOf((*MockHarness)(nil).RunToolCall), session, toolCall, targetTool, args, model)
}

// SetCurrRoundMessages mocks base method.
func (m *MockHarness) SetCurrRoundMessages(messages *core.Conversation, message core.ReActMessage, windowSize, skip int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCurrRoundMessages", messages, message, windowSize, skip)
}

// SetCurrRoundMessages indicates an expected call of SetCurrRoundMessages.
func (mr *MockHarnessMockRecorder) SetCurrRoundMessages(messages, message, windowSize, skip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrRoundMessages", reflect.TypeOf((*MockHarness)(nil).SetCurrRoundMessages), messages, message, windowSize, skip)
}

// SetFinalQuery mocks base method.
func (m *MockHarness) SetFinalQuery(question *core.Question, knowledge, splitter string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFinalQuery", question, knowledge, splitter)
}

// SetFinalQuery indicates an expected call of SetFinalQuery.
func (mr *MockHarnessMockRecorder) SetFinalQuery(question, knowledge, splitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFinalQuery", reflect.TypeOf((*MockHarness)(nil).SetFinalQuery), question, knowledge, splitter)
}

// SetNextRoundMessages mocks base method.
func (m *MockHarness) SetNextRoundMessages(question *core.Question, messages *core.Conversation) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNextRoundMessages", question, messages)
}

// SetNextRoundMessages indicates an expected call of SetNextRoundMessages.
func (mr *MockHarnessMockRecorder) SetNextRoundMessages(question, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNextRoundMessages", reflect.TypeOf((*MockHarness)(nil).SetNextRoundMessages), question, messages)
}
