// Code generated by MockGen. DO NOT EDIT.
// Source: core/session.go
//
// Generated by this command:
//
//	mockgen -source=core/session.go -destination=test/mock/mock_session.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// BeforeStart mocks base method.
func (m *MockSession) BeforeStart(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStart", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStart indicates an expected call of BeforeStart.
func (mr *MockSessionMockRecorder) BeforeStart(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStart", reflect.TypeOf((*MockSession)(nil).BeforeStart), arg0)
}

// BeforeStop mocks base method.
func (m *MockSession) BeforeStop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStop indicates an expected call of BeforeStop.
func (mr *MockSessionMockRecorder) BeforeStop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStop", reflect.TypeOf((*MockSession)(nil).BeforeStop), arg0)
}

// ClearToolConfirmed mocks base method.
func (m *MockSession) ClearToolConfirmed(serverName, toolName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearToolConfirmed", serverName, toolName)
}

// ClearToolConfirmed indicates an expected call of ClearToolConfirmed.
func (mr *MockSessionMockRecorder) ClearToolConfirmed(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearToolConfirmed", reflect.TypeOf((*MockSession)(nil).ClearToolConfirmed), serverName, toolName)
}

// CloseBenchmarkListeningChannels mocks base method.
func (m *MockSession) CloseBenchmarkListeningChannels() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseBenchmarkListeningChannels")
}

// CloseBenchmarkListeningChannels indicates an expected call of CloseBenchmarkListeningChannels.
func (mr *MockSessionMockRecorder) CloseBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseBenchmarkListeningChannels", reflect.TypeOf((*MockSession)(nil).CloseBenchmarkListeningChannels))
}

// DeletePendingMCPToolCall mocks base method.
func (m *MockSession) DeletePendingMCPToolCall(serverName, toolName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeletePendingMCPToolCall", serverName, toolName)
}

// DeletePendingMCPToolCall indicates an expected call of DeletePendingMCPToolCall.
func (mr *MockSessionMockRecorder) DeletePendingMCPToolCall(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingMCPToolCall", reflect.TypeOf((*MockSession)(nil).DeletePendingMCPToolCall), serverName, toolName)
}

// GetBenchmarkListeningChannels mocks base method.
func (m *MockSession) GetBenchmarkListeningChannels() map[string]chan core.StatEvent[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBenchmarkListeningChannels")
	ret0, _ := ret[0].(map[string]chan core.StatEvent[any])
	return ret0
}

// GetBenchmarkListeningChannels indicates an expected call of GetBenchmarkListeningChannels.
func (mr *MockSessionMockRecorder) GetBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBenchmarkListeningChannels", reflect.TypeOf((*MockSession)(nil).GetBenchmarkListeningChannels))
}

// GetConfigs mocks base method.
func (m *MockSession) GetConfigs() core.SessionConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigs")
	ret0, _ := ret[0].(core.SessionConfig)
	return ret0
}

// GetConfigs indicates an expected call of GetConfigs.
func (mr *MockSessionMockRecorder) GetConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigs", reflect.TypeOf((*MockSession)(nil).GetConfigs))
}

// GetContext mocks base method.
func (m *MockSession) GetContext() core.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(core.Context)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockSessionMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockSession)(nil).GetContext))
}

// GetQueryCtx mocks base method.
func (m *MockSession) GetQueryCtx() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryCtx")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// GetQueryCtx indicates an expected call of GetQueryCtx.
func (mr *MockSessionMockRecorder) GetQueryCtx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryCtx", reflect.TypeOf((*MockSession)(nil).GetQueryCtx))
}

// CancelQuery mocks base method.
func (m *MockSession) CancelQuery() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelQuery")
}

// CancelQuery indicates an expected call of CancelQuery.
func (mr *MockSessionMockRecorder) CancelQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelQuery", reflect.TypeOf((*MockSession)(nil).CancelQuery))
}

// Acquire mocks base method.
func (m *MockSession) Acquire() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Acquire indicates an expected call of Acquire.
func (mr *MockSessionMockRecorder) Acquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockSession)(nil).Acquire))
}

// Release mocks base method.
func (m *MockSession) Release() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockSessionMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockSession)(nil).Release))
}

// SetQueryContext mocks base method.
func (m *MockSession) SetQueryContext(ctx context.Context, cancel context.CancelFunc) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetQueryContext", ctx, cancel)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetQueryContext indicates an expected call of SetQueryContext.
func (mr *MockSessionMockRecorder) SetQueryContext(ctx, cancel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQueryContext", reflect.TypeOf((*MockSession)(nil).SetQueryContext), ctx, cancel)
}

// DeleteMemory mocks base method.
func (m *MockSession) DeleteMemory() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteMemory")
}

// DeleteMemory indicates an expected call of DeleteMemory.
func (mr *MockSessionMockRecorder) DeleteMemory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMemory", reflect.TypeOf((*MockSession)(nil).DeleteMemory))
}

// GetConversation mocks base method.
func (m *MockSession) GetConversation() *core.Conversation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversation")
	ret0, _ := ret[0].(*core.Conversation)
	return ret0
}

// GetConversation indicates an expected call of GetConversation.
func (mr *MockSessionMockRecorder) GetConversation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversation", reflect.TypeOf((*MockSession)(nil).GetConversation))
}

// GetEventChans mocks base method.
func (m *MockSession) GetEventChans() map[string]chan core.Event[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventChans")
	ret0, _ := ret[0].(map[string]chan core.Event[any])
	return ret0
}

// GetEventChans indicates an expected call of GetEventChans.
func (mr *MockSessionMockRecorder) GetEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventChans", reflect.TypeOf((*MockSession)(nil).GetEventChans))
}

// GetID mocks base method.
func (m *MockSession) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSessionMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSession)(nil).GetID))
}

// GetLoadTools mocks base method.
func (m *MockSession) GetLoadTools() *[]core.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadTools")
	ret0, _ := ret[0].(*[]core.Tool)
	return ret0
}

// GetLoadTools indicates an expected call of GetLoadTools.
func (mr *MockSessionMockRecorder) GetLoadTools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadTools", reflect.TypeOf((*MockSession)(nil).GetLoadTools))
}

// GetModelProviders mocks base method.
func (m *MockSession) GetModelProviders() []core.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProviders")
	ret0, _ := ret[0].([]core.Provider)
	return ret0
}

// GetModelProviders indicates an expected call of GetModelProviders.
func (mr *MockSessionMockRecorder) GetModelProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProviders", reflect.TypeOf((*MockSession)(nil).GetModelProviders))
}

// GetPendingMCPToolCall mocks base method.
func (m *MockSession) GetPendingMCPToolCall(serverName, toolName string) *core.PendingMCPToolCall {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingMCPToolCall", serverName, toolName)
	ret0, _ := ret[0].(*core.PendingMCPToolCall)
	return ret0
}

// GetPendingMCPToolCall indicates an expected call of GetPendingMCPToolCall.
func (mr *MockSessionMockRecorder) GetPendingMCPToolCall(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingMCPToolCall", reflect.TypeOf((*MockSession)(nil).GetPendingMCPToolCall), serverName, toolName)
}

// GetQuestionChan mocks base method.
func (m *MockSession) GetQuestionChan() chan core.Question {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionChan")
	ret0, _ := ret[0].(chan core.Question)
	return ret0
}

// GetQuestionChan indicates an expected call of GetQuestionChan.
func (mr *MockSessionMockRecorder) GetQuestionChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionChan", reflect.TypeOf((*MockSession)(nil).GetQuestionChan))
}

// GetStatus mocks base method.
func (m *MockSession) GetStatus() core.SessionStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(core.SessionStatus)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockSessionMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockSession)(nil).GetStatus))
}

// IsToolConfirmed mocks base method.
func (m *MockSession) IsToolConfirmed(serverName, toolName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsToolConfirmed", serverName, toolName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsToolConfirmed indicates an expected call of IsToolConfirmed.
func (mr *MockSessionMockRecorder) IsToolConfirmed(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsToolConfirmed", reflect.TypeOf((*MockSession)(nil).IsToolConfirmed), serverName, toolName)
}

// NewSubSession mocks base method.
func (m *MockSession) NewSubSession() core.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSubSession")
	ret0, _ := ret[0].(core.Session)
	return ret0
}

// NewSubSession indicates an expected call of NewSubSession.
func (mr *MockSessionMockRecorder) NewSubSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSubSession", reflect.TypeOf((*MockSession)(nil).NewSubSession))
}

// OnEvent mocks base method.
func (m *MockSession) OnEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEvent")
}

// OnEvent indicates an expected call of OnEvent.
func (mr *MockSessionMockRecorder) OnEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEvent", reflect.TypeOf((*MockSession)(nil).OnEvent))
}

// ProcessQuery mocks base method.
func (m *MockSession) ProcessQuery(query core.Question) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessQuery", query)
}

// ProcessQuery indicates an expected call of ProcessQuery.
func (mr *MockSessionMockRecorder) ProcessQuery(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessQuery", reflect.TypeOf((*MockSession)(nil).ProcessQuery), query)
}

// RegisterEventChans mocks base method.
func (m *MockSession) RegisterEventChans() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEventChans")
}

// RegisterEventChans indicates an expected call of RegisterEventChans.
func (mr *MockSessionMockRecorder) RegisterEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventChans", reflect.TypeOf((*MockSession)(nil).RegisterEventChans))
}

// SaveMemory mocks base method.
func (m *MockSession) SaveMemory(arg0 core.ReActMessage) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMemory", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SaveMemory indicates an expected call of SaveMemory.
func (mr *MockSessionMockRecorder) SaveMemory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMemory", reflect.TypeOf((*MockSession)(nil).SaveMemory), arg0)
}

// SelectLocalKB mocks base method.
func (m *MockSession) SelectLocalKB(arg0 core.Question) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectLocalKB", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectLocalKB indicates an expected call of SelectLocalKB.
func (mr *MockSessionMockRecorder) SelectLocalKB(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectLocalKB", reflect.TypeOf((*MockSession)(nil).SelectLocalKB), arg0)
}

// SetLoadTools mocks base method.
func (m *MockSession) SetLoadTools(tool core.Tool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLoadTools", tool)
}

// SetLoadTools indicates an expected call of SetLoadTools.
func (mr *MockSessionMockRecorder) SetLoadTools(tool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoadTools", reflect.TypeOf((*MockSession)(nil).SetLoadTools), tool)
}

// SetLogger mocks base method.
func (m *MockSession) SetLogger(arg0 core.SessionConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogger", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockSessionMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockSession)(nil).SetLogger), arg0)
}

// SetPendingMCPToolCall mocks base method.
func (m *MockSession) SetPendingMCPToolCall(serverName, toolName string, pending *core.PendingMCPToolCall) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPendingMCPToolCall", serverName, toolName, pending)
}

// SetPendingMCPToolCall indicates an expected call of SetPendingMCPToolCall.
func (mr *MockSessionMockRecorder) SetPendingMCPToolCall(serverName, toolName, pending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPendingMCPToolCall", reflect.TypeOf((*MockSession)(nil).SetPendingMCPToolCall), serverName, toolName, pending)
}

// SetStatus mocks base method.
func (m *MockSession) SetStatus(status core.SessionStatus) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", status)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockSessionMockRecorder) SetStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockSession)(nil).SetStatus), status)
}

// SetToolConfirmed mocks base method.
func (m *MockSession) SetToolConfirmed(serverName, toolName, answer string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToolConfirmed", serverName, toolName, answer)
}

// SetToolConfirmed indicates an expected call of SetToolConfirmed.
func (mr *MockSessionMockRecorder) SetToolConfirmed(serverName, toolName, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToolConfirmed", reflect.TypeOf((*MockSession)(nil).SetToolConfirmed), serverName, toolName, answer)
}

// Start mocks base method.
func (m *MockSession) Start(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSessionMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSession)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockSession) Stop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSessionMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSession)(nil).Stop), arg0)
}

// MockToolConfirmManager is a mock of ToolConfirmManager interface.
type MockToolConfirmManager struct {
	ctrl     *gomock.Controller
	recorder *MockToolConfirmManagerMockRecorder
	isgomock struct{}
}

// MockToolConfirmManagerMockRecorder is the mock recorder for MockToolConfirmManager.
type MockToolConfirmManagerMockRecorder struct {
	mock *MockToolConfirmManager
}

// NewMockToolConfirmManager creates a new mock instance.
func NewMockToolConfirmManager(ctrl *gomock.Controller) *MockToolConfirmManager {
	mock := &MockToolConfirmManager{ctrl: ctrl}
	mock.recorder = &MockToolConfirmManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolConfirmManager) EXPECT() *MockToolConfirmManagerMockRecorder {
	return m.recorder
}

// ClearToolConfirmed mocks base method.
func (m *MockToolConfirmManager) ClearToolConfirmed(serverName, toolName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearToolConfirmed", serverName, toolName)
}

// ClearToolConfirmed indicates an expected call of ClearToolConfirmed.
func (mr *MockToolConfirmManagerMockRecorder) ClearToolConfirmed(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearToolConfirmed", reflect.TypeOf((*MockToolConfirmManager)(nil).ClearToolConfirmed), serverName, toolName)
}

// DeletePendingMCPToolCall mocks base method.
func (m *MockToolConfirmManager) DeletePendingMCPToolCall(serverName, toolName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeletePendingMCPToolCall", serverName, toolName)
}

// DeletePendingMCPToolCall indicates an expected call of DeletePendingMCPToolCall.
func (mr *MockToolConfirmManagerMockRecorder) DeletePendingMCPToolCall(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingMCPToolCall", reflect.TypeOf((*MockToolConfirmManager)(nil).DeletePendingMCPToolCall), serverName, toolName)
}

// GetPendingMCPToolCall mocks base method.
func (m *MockToolConfirmManager) GetPendingMCPToolCall(serverName, toolName string) *core.PendingMCPToolCall {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingMCPToolCall", serverName, toolName)
	ret0, _ := ret[0].(*core.PendingMCPToolCall)
	return ret0
}

// GetPendingMCPToolCall indicates an expected call of GetPendingMCPToolCall.
func (mr *MockToolConfirmManagerMockRecorder) GetPendingMCPToolCall(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingMCPToolCall", reflect.TypeOf((*MockToolConfirmManager)(nil).GetPendingMCPToolCall), serverName, toolName)
}

// IsToolConfirmed mocks base method.
func (m *MockToolConfirmManager) IsToolConfirmed(serverName, toolName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsToolConfirmed", serverName, toolName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsToolConfirmed indicates an expected call of IsToolConfirmed.
func (mr *MockToolConfirmManagerMockRecorder) IsToolConfirmed(serverName, toolName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsToolConfirmed", reflect.TypeOf((*MockToolConfirmManager)(nil).IsToolConfirmed), serverName, toolName)
}

// SetPendingMCPToolCall mocks base method.
func (m *MockToolConfirmManager) SetPendingMCPToolCall(serverName, toolName string, pending *core.PendingMCPToolCall) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPendingMCPToolCall", serverName, toolName, pending)
}

// SetPendingMCPToolCall indicates an expected call of SetPendingMCPToolCall.
func (mr *MockToolConfirmManagerMockRecorder) SetPendingMCPToolCall(serverName, toolName, pending any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPendingMCPToolCall", reflect.TypeOf((*MockToolConfirmManager)(nil).SetPendingMCPToolCall), serverName, toolName, pending)
}

// SetToolConfirmed mocks base method.
func (m *MockToolConfirmManager) SetToolConfirmed(serverName, toolName, answer string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToolConfirmed", serverName, toolName, answer)
}

// SetToolConfirmed indicates an expected call of SetToolConfirmed.
func (mr *MockToolConfirmManagerMockRecorder) SetToolConfirmed(serverName, toolName, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToolConfirmed", reflect.TypeOf((*MockToolConfirmManager)(nil).SetToolConfirmed), serverName, toolName, answer)
}

// MockSessionAnswer is a mock of SessionAnswer interface.
type MockSessionAnswer struct {
	ctrl     *gomock.Controller
	recorder *MockSessionAnswerMockRecorder
	isgomock struct{}
}

// MockSessionAnswerMockRecorder is the mock recorder for MockSessionAnswer.
type MockSessionAnswerMockRecorder struct {
	mock *MockSessionAnswer
}

// NewMockSessionAnswer creates a new mock instance.
func NewMockSessionAnswer(ctrl *gomock.Controller) *MockSessionAnswer {
	mock := &MockSessionAnswer{ctrl: ctrl}
	mock.recorder = &MockSessionAnswerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionAnswer) EXPECT() *MockSessionAnswerMockRecorder {
	return m.recorder
}

// GetSessionID mocks base method.
func (m *MockSessionAnswer) GetSessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSessionID indicates an expected call of GetSessionID.
func (mr *MockSessionAnswerMockRecorder) GetSessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionID", reflect.TypeOf((*MockSessionAnswer)(nil).GetSessionID))
}

// ToString mocks base method.
func (m *MockSessionAnswer) ToString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockSessionAnswerMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockSessionAnswer)(nil).ToString))
}
