// Code generated by MockGen. DO NOT EDIT.
// Source: core/provider.go
//
// Generated by this command:
//
//	mockgen -source=core/provider.go -destination=test/mock/mock_provider.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestion is a mock of Question interface.
type MockQuestion struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionMockRecorder
	isgomock struct{}
}

// MockQuestionMockRecorder is the mock recorder for MockQuestion.
type MockQuestionMockRecorder struct {
	mock *MockQuestion
}

// NewMockQuestion creates a new mock instance.
func NewMockQuestion(ctrl *gomock.Controller) *MockQuestion {
	mock := &MockQuestion{ctrl: ctrl}
	mock.recorder = &MockQuestionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestion) EXPECT() *MockQuestionMockRecorder {
	return m.recorder
}

// GetDefaultAnswer mocks base method.
func (m *MockQuestion) GetDefaultAnswer() core.Answer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultAnswer")
	ret0, _ := ret[0].(core.Answer)
	return ret0
}

// GetDefaultAnswer indicates an expected call of GetDefaultAnswer.
func (mr *MockQuestionMockRecorder) GetDefaultAnswer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultAnswer", reflect.TypeOf((*MockQuestion)(nil).GetDefaultAnswer))
}

// GetHintChan mocks base method.
func (m *MockQuestion) GetHintChan() chan core.Answer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHintChan")
	ret0, _ := ret[0].(chan core.Answer)
	return ret0
}

// GetHintChan indicates an expected call of GetHintChan.
func (mr *MockQuestionMockRecorder) GetHintChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHintChan", reflect.TypeOf((*MockQuestion)(nil).GetHintChan))
}

// GetID mocks base method.
func (m *MockQuestion) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockQuestionMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockQuestion)(nil).GetID))
}

// GetProviderName mocks base method.
func (m *MockQuestion) GetProviderName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProviderName indicates an expected call of GetProviderName.
func (mr *MockQuestionMockRecorder) GetProviderName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderName", reflect.TypeOf((*MockQuestion)(nil).GetProviderName))
}

// GetQuery mocks base method.
func (m *MockQuestion) GetQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockQuestionMockRecorder) GetQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockQuestion)(nil).GetQuery))
}

// GetResponseChan mocks base method.
func (m *MockQuestion) GetResponseChan() chan core.Answer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseChan")
	ret0, _ := ret[0].(chan core.Answer)
	return ret0
}

// GetResponseChan indicates an expected call of GetResponseChan.
func (mr *MockQuestionMockRecorder) GetResponseChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseChan", reflect.TypeOf((*MockQuestion)(nil).GetResponseChan))
}

// GetRetryQuery mocks base method.
func (m *MockQuestion) GetRetryQuery() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetryQuery")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRetryQuery indicates an expected call of GetRetryQuery.
func (mr *MockQuestionMockRecorder) GetRetryQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetryQuery", reflect.TypeOf((*MockQuestion)(nil).GetRetryQuery))
}

// GetSessionID mocks base method.
func (m *MockQuestion) GetSessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSessionID indicates an expected call of GetSessionID.
func (mr *MockQuestionMockRecorder) GetSessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionID", reflect.TypeOf((*MockQuestion)(nil).GetSessionID))
}

// SetQuery mocks base method.
func (m *MockQuestion) SetQuery(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetQuery", arg0)
}

// SetQuery indicates an expected call of SetQuery.
func (mr *MockQuestionMockRecorder) SetQuery(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQuery", reflect.TypeOf((*MockQuestion)(nil).SetQuery), arg0)
}

// ToString mocks base method.
func (m *MockQuestion) ToString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockQuestionMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockQuestion)(nil).ToString))
}

// MockAnswer is a mock of Answer interface.
type MockAnswer struct {
	ctrl     *gomock.Controller
	recorder *MockAnswerMockRecorder
	isgomock struct{}
}

// MockAnswerMockRecorder is the mock recorder for MockAnswer.
type MockAnswerMockRecorder struct {
	mock *MockAnswer
}

// NewMockAnswer creates a new mock instance.
func NewMockAnswer(ctrl *gomock.Controller) *MockAnswer {
	mock := &MockAnswer{ctrl: ctrl}
	mock.recorder = &MockAnswerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswer) EXPECT() *MockAnswerMockRecorder {
	return m.recorder
}

// ToString mocks base method.
func (m *MockAnswer) ToString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockAnswerMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockAnswer)(nil).ToString))
}

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockProvider) Auth(arg0 core.ModelConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockProviderMockRecorder) Auth(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockProvider)(nil).Auth), arg0)
}

// Complete mocks base method.
func (m *MockProvider) Complete(messages []core.ReActMessage, tools []core.Tool) (core.Answer, []core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", messages, tools)
	ret0, _ := ret[0].(core.Answer)
	ret1, _ := ret[1].([]core.Diagnostic)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockProviderMockRecorder) Complete(messages, tools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockProvider)(nil).Complete), messages, tools)
}

// GetID mocks base method.
func (m *MockProvider) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockProviderMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockProvider)(nil).GetID))
}

// GetModelConfig mocks base method.
func (m *MockProvider) GetModelConfig() core.ModelConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelConfig")
	ret0, _ := ret[0].(core.ModelConfig)
	return ret0
}

// GetModelConfig indicates an expected call of GetModelConfig.
func (mr *MockProviderMockRecorder) GetModelConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelConfig", reflect.TypeOf((*MockProvider)(nil).GetModelConfig))
}

// GetName mocks base method.
func (m *MockProvider) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockProviderMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockProvider)(nil).GetName))
}

// Init mocks base method.
func (m *MockProvider) Init(arg0 core.ModelConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockProviderMockRecorder) Init(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockProvider)(nil).Init), arg0)
}
