// Code generated by MockGen. DO NOT EDIT.
// Source: core/app.go
//
// Generated by this command:
//
//	mockgen -source=core/app.go -destination=test/mock_app.go -package=test
//

// Package test is a generated GoMock package.
package mock

import (
	"log"
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceProvider is a mock of ServiceProvider interface.
type MockServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderMockRecorder
	isgomock struct{}
}

// MockServiceProviderMockRecorder is the mock recorder for MockServiceProvider.
type MockServiceProviderMockRecorder struct {
	mock *MockServiceProvider
}

// NewMockServiceProvider creates a new mock instance.
func NewMockServiceProvider(ctrl *gomock.Controller) *MockServiceProvider {
	mock := &MockServiceProvider{ctrl: ctrl}
	mock.recorder = &MockServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceProvider) EXPECT() *MockServiceProviderMockRecorder {
	return m.recorder
}

// MockSingalManager is a mock of SingalManager interface.
type MockSingalManager struct {
	ctrl     *gomock.Controller
	recorder *MockSingalManagerMockRecorder
	isgomock struct{}
}

// MockSingalManagerMockRecorder is the mock recorder for MockSingalManager.
type MockSingalManagerMockRecorder struct {
	mock *MockSingalManager
}

// NewMockSingalManager creates a new mock instance.
func NewMockSingalManager(ctrl *gomock.Controller) *MockSingalManager {
	mock := &MockSingalManager{ctrl: ctrl}
	mock.recorder = &MockSingalManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSingalManager) EXPECT() *MockSingalManagerMockRecorder {
	return m.recorder
}

// GracefulQuit mocks base method.
// auto-added: GracefulQuit mocks base method.
func (m *MockSingalManager) GracefulQuit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulQuit")
}

// auto-added: GracefulQuit indicates an expected call of GracefulQuit.
func (mr *MockSingalManagerMockRecorder) GracefulQuit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulQuit", reflect.TypeOf((*MockSingalManager)(nil).GracefulQuit))
}

// MockAgentServer is a mock of AgentServer interface.
type MockAgentServer struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServerMockRecorder
	isgomock struct{}
}

// MockAgentServerMockRecorder is the mock recorder for MockAgentServer.
type MockAgentServerMockRecorder struct {
	mock *MockAgentServer
}

// NewMockAgentServer creates a new mock instance.
func NewMockAgentServer(ctrl *gomock.Controller) *MockAgentServer {
	mock := &MockAgentServer{ctrl: ctrl}
	mock.recorder = &MockAgentServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServer) EXPECT() *MockAgentServerMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockAgentServer) Acquire() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Acquire indicates an expected call of Acquire.
func (mr *MockAgentServerMockRecorder) Acquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockAgentServer)(nil).Acquire))
}

// BeforeStart mocks base method.
func (m *MockAgentServer) BeforeStart(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStart", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStart indicates an expected call of BeforeStart.
func (mr *MockAgentServerMockRecorder) BeforeStart(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStart", reflect.TypeOf((*MockAgentServer)(nil).BeforeStart), arg0)
}

// BeforeStop mocks base method.
func (m *MockAgentServer) BeforeStop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStop indicates an expected call of BeforeStop.
func (mr *MockAgentServerMockRecorder) BeforeStop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStop", reflect.TypeOf((*MockAgentServer)(nil).BeforeStop), arg0)
}

// CloseBenchmarkListeningChannels mocks base method.
func (m *MockAgentServer) CloseBenchmarkListeningChannels() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseBenchmarkListeningChannels")
}

// CloseBenchmarkListeningChannels indicates an expected call of CloseBenchmarkListeningChannels.
func (mr *MockAgentServerMockRecorder) CloseBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseBenchmarkListeningChannels", reflect.TypeOf((*MockAgentServer)(nil).CloseBenchmarkListeningChannels))
}

// GetBenchmarkListeningChannels mocks base method.
func (m *MockAgentServer) GetBenchmarkListeningChannels() map[string]chan core.StatEvent[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBenchmarkListeningChannels")
	ret0, _ := ret[0].(map[string]chan core.StatEvent[any])
	return ret0
}

// GetBenchmarkListeningChannels indicates an expected call of GetBenchmarkListeningChannels.
func (mr *MockAgentServerMockRecorder) GetBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBenchmarkListeningChannels", reflect.TypeOf((*MockAgentServer)(nil).GetBenchmarkListeningChannels))
}

// auto-added: GetAgentCore mocks base method.
func (m *MockAgentServer) GetAgentCore() core.AgentCore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCore")
	ret0, _ := ret[0].(core.AgentCore)
	return ret0
}

// auto-added: GetAgentCore indicates an expected call of GetAgentCore.
func (mr *MockAgentServerMockRecorder) GetAgentCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCore", reflect.TypeOf((*MockAgentServer)(nil).GetAgentCore))
}

// auto-added: GetAppConfig mocks base method.
func (m *MockAgentServer) GetAppConfig() core.AppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppConfig")
	ret0, _ := ret[0].(core.AppConfig)
	return ret0
}

// auto-added: GetAppConfig indicates an expected call of GetAppConfig.
func (mr *MockAgentServerMockRecorder) GetAppConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppConfig", reflect.TypeOf((*MockAgentServer)(nil).GetAppConfig))
}

// GetConfigPath mocks base method.
func (m *MockAgentServer) GetConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockAgentServerMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockAgentServer)(nil).GetConfigPath))
}

// GetEventChans mocks base method.
func (m *MockAgentServer) GetEventChans() map[string]chan core.Event[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventChans")
	ret0, _ := ret[0].(map[string]chan core.Event[any])
	return ret0
}

// GetEventChans indicates an expected call of GetEventChans.
func (mr *MockAgentServerMockRecorder) GetEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventChans", reflect.TypeOf((*MockAgentServer)(nil).GetEventChans))
}

// GetHistory mocks base method.
func (m *MockAgentServer) GetHistory() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockAgentServerMockRecorder) GetHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockAgentServer)(nil).GetHistory))
}

// GetID mocks base method.
func (m *MockAgentServer) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAgentServerMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAgentServer)(nil).GetID))
}

// GetKnowledgeBase mocks base method.
func (m *MockAgentServer) GetKnowledgeBase() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockAgentServerMockRecorder) GetKnowledgeBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockAgentServer)(nil).GetKnowledgeBase))
}

// auto-added: GetLogger mocks base method.
func (m *MockAgentServer) GetLogger() *log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*log.Logger)
	return ret0
}

// auto-added: GetLogger indicates an expected call of GetLogger.
func (mr *MockAgentServerMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockAgentServer)(nil).GetLogger))
}

// GetModelProviders mocks base method.
func (m *MockAgentServer) GetModelProviders() []core.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProviders")
	ret0, _ := ret[0].([]core.Provider)
	return ret0
}

// GetModelProviders indicates an expected call of GetModelProviders.
func (mr *MockAgentServerMockRecorder) GetModelProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProviders", reflect.TypeOf((*MockAgentServer)(nil).GetModelProviders))
}

// GetPrompt mocks base method.
func (m *MockAgentServer) GetPrompt() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockAgentServerMockRecorder) GetPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockAgentServer)(nil).GetPrompt))
}

// GetSessionConfig mocks base method.
func (m *MockAgentServer) GetSessionConfig() core.SessionConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionConfig")
	ret0, _ := ret[0].(core.SessionConfig)
	return ret0
}

// GetSessionConfig indicates an expected call of GetSessionConfig.
func (mr *MockAgentServerMockRecorder) GetSessionConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionConfig", reflect.TypeOf((*MockAgentServer)(nil).GetSessionConfig))
}

// GetSessionOnCreate mocks base method.
func (m *MockAgentServer) GetSessionOnCreate(arg0 string, arg1 bool) (core.Session, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionOnCreate", arg0, arg1)
	ret0, _ := ret[0].(core.Session)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// GetSessionOnCreate indicates an expected call of GetSessionOnCreate.
func (mr *MockAgentServerMockRecorder) GetSessionOnCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionOnCreate", reflect.TypeOf((*MockAgentServer)(nil).GetSessionOnCreate), arg0, arg1)
}

// GetSkills mocks base method.
func (m *MockAgentServer) GetSkills() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkills")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetSkills indicates an expected call of GetSkills.
func (mr *MockAgentServerMockRecorder) GetSkills() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkills", reflect.TypeOf((*MockAgentServer)(nil).GetSkills))
}

// GetToolsConfig mocks base method.
func (m *MockAgentServer) GetToolsConfig() []core.ToolConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolsConfig")
	ret0, _ := ret[0].([]core.ToolConfig)
	return ret0
}

// GetToolsConfig indicates an expected call of GetToolsConfig.
func (mr *MockAgentServerMockRecorder) GetToolsConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolsConfig", reflect.TypeOf((*MockAgentServer)(nil).GetToolsConfig))
}

// auto-added: GracefulQuit mocks base method.
func (m *MockAgentServer) GracefulQuit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulQuit")
}

// auto-added: GracefulQuit indicates an expected call of GracefulQuit.
func (mr *MockAgentServerMockRecorder) GracefulQuit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulQuit", reflect.TypeOf((*MockAgentServer)(nil).GracefulQuit))
}

// LoadConfigs mocks base method.
func (m *MockAgentServer) LoadConfigs(path string) (core.AgentCoreConfig, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigs", path)
	ret0, _ := ret[0].(core.AgentCoreConfig)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// LoadConfigs indicates an expected call of LoadConfigs.
func (mr *MockAgentServerMockRecorder) LoadConfigs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigs", reflect.TypeOf((*MockAgentServer)(nil).LoadConfigs), path)
}

// OnEvent mocks base method.
func (m *MockAgentServer) OnEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEvent")
}

// OnEvent indicates an expected call of OnEvent.
func (mr *MockAgentServerMockRecorder) OnEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEvent", reflect.TypeOf((*MockAgentServer)(nil).OnEvent))
}

// RegisterEventChans mocks base method.
func (m *MockAgentServer) RegisterEventChans() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEventChans")
}

// RegisterEventChans indicates an expected call of RegisterEventChans.
func (mr *MockAgentServerMockRecorder) RegisterEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventChans", reflect.TypeOf((*MockAgentServer)(nil).RegisterEventChans))
}

// Release mocks base method.
func (m *MockAgentServer) Release() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockAgentServerMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAgentServer)(nil).Release))
}

// auto-added: SetAgentCore mocks base method.
func (m *MockAgentServer) SetAgentCore(arg0 core.AgentCore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAgentCore", arg0)
}

// auto-added: SetAgentCore indicates an expected call of SetAgentCore.
func (mr *MockAgentServerMockRecorder) SetAgentCore(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentCore", reflect.TypeOf((*MockAgentServer)(nil).SetAgentCore), arg0)
}

// auto-added: SetAppConfig mocks base method.
func (m *MockAgentServer) SetAppConfig(arg0 core.AppConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppConfig", arg0)
}

// auto-added: SetAppConfig indicates an expected call of SetAppConfig.
func (mr *MockAgentServerMockRecorder) SetAppConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppConfig", reflect.TypeOf((*MockAgentServer)(nil).SetAppConfig), arg0)
}

// SetHistory mocks base method.
func (m *MockAgentServer) SetHistory(arg0 core.HistoryConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockAgentServerMockRecorder) SetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockAgentServer)(nil).SetHistory), arg0)
}

// SetID mocks base method.
func (m *MockAgentServer) SetID() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetID")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetID indicates an expected call of SetID.
func (mr *MockAgentServerMockRecorder) SetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockAgentServer)(nil).SetID))
}

// SetKnowledgeBase mocks base method.
func (m *MockAgentServer) SetKnowledgeBase(arg0 core.KnowledgeBaseConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKnowledgeBase", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetKnowledgeBase indicates an expected call of SetKnowledgeBase.
func (mr *MockAgentServerMockRecorder) SetKnowledgeBase(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKnowledgeBase", reflect.TypeOf((*MockAgentServer)(nil).SetKnowledgeBase), arg0)
}

// SetLanguage mocks base method.
func (m *MockAgentServer) SetLanguage(arg0 core.LanguageType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLanguage", arg0)
}

// SetLanguage indicates an expected call of SetLanguage.
func (mr *MockAgentServerMockRecorder) SetLanguage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLanguage", reflect.TypeOf((*MockAgentServer)(nil).SetLanguage), arg0)
}

// auto-added: SetLogger mocks base method.
func (m *MockAgentServer) SetLogger(arg0 *log.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", arg0)
}

// auto-added: SetLogger indicates an expected call of SetLogger.
func (mr *MockAgentServerMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockAgentServer)(nil).SetLogger), arg0)
}

// SetPrompt mocks base method.
func (m *MockAgentServer) SetPrompt(arg0 core.PromptConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrompt", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetPrompt indicates an expected call of SetPrompt.
func (mr *MockAgentServerMockRecorder) SetPrompt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrompt", reflect.TypeOf((*MockAgentServer)(nil).SetPrompt), arg0)
}

// auto-added: SetRouter mocks base method.
func (m *MockAgentServer) SetRouter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRouter")
}

// auto-added: SetRouter indicates an expected call of SetRouter.
func (mr *MockAgentServerMockRecorder) SetRouter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRouter", reflect.TypeOf((*MockAgentServer)(nil).SetRouter))
}

// SetSkills mocks base method.
func (m *MockAgentServer) SetSkills(arg0 core.SkillConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSkills", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetSkills indicates an expected call of SetSkills.
func (mr *MockAgentServerMockRecorder) SetSkills(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSkills", reflect.TypeOf((*MockAgentServer)(nil).SetSkills), arg0)
}

// auto-added: Start mocks base method.
func (m *MockAgentServer) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// auto-added: Start indicates an expected call of Start.
func (mr *MockAgentServerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAgentServer)(nil).Start))
}

// auto-added: Stop mocks base method.
func (m *MockAgentServer) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// auto-added: Stop indicates an expected call of Stop.
func (mr *MockAgentServerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAgentServer)(nil).Stop))
}

// StopSession mocks base method.
func (m *MockAgentServer) StopSession(arg0 string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSession", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// StopSession indicates an expected call of StopSession.
func (mr *MockAgentServerMockRecorder) StopSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSession", reflect.TypeOf((*MockAgentServer)(nil).StopSession), arg0)
}

// MockUserManager is a mock of UserManager interface.
type MockUserManager struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagerMockRecorder
	isgomock struct{}
}

// MockUserManagerMockRecorder is the mock recorder for MockUserManager.
type MockUserManagerMockRecorder struct {
	mock *MockUserManager
}

// NewMockUserManager creates a new mock instance.
func NewMockUserManager(ctrl *gomock.Controller) *MockUserManager {
	mock := &MockUserManager{ctrl: ctrl}
	mock.recorder = &MockUserManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManager) EXPECT() *MockUserManagerMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockUserManager) AuthUser(token string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", token)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockUserManagerMockRecorder) AuthUser(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockUserManager)(nil).AuthUser), token)
}

// CheckUserPlan mocks base method.
func (m *MockUserManager) CheckUserPlan(arg0 core.AgentConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPlan", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// CheckUserPlan indicates an expected call of CheckUserPlan.
func (mr *MockUserManagerMockRecorder) CheckUserPlan(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPlan", reflect.TypeOf((*MockUserManager)(nil).CheckUserPlan), arg0)
}

// SetModelProviders mocks base method.
func (m *MockUserManager) SetModelProviders(modelConfigs []core.ModelConfig, appConfig core.AppConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModelProviders", modelConfigs, appConfig)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetModelProviders indicates an expected call of SetModelProviders.
func (mr *MockUserManagerMockRecorder) SetModelProviders(modelConfigs, appConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModelProviders", reflect.TypeOf((*MockUserManager)(nil).SetModelProviders), modelConfigs, appConfig)
}

// MockAgentApp is a mock of AgentApp interface.
type MockAgentApp struct {
	ctrl     *gomock.Controller
	recorder *MockAgentAppMockRecorder
	isgomock struct{}
}

// MockAgentAppMockRecorder is the mock recorder for MockAgentApp.
type MockAgentAppMockRecorder struct {
	mock *MockAgentApp
}

// NewMockAgentApp creates a new mock instance.
func NewMockAgentApp(ctrl *gomock.Controller) *MockAgentApp {
	mock := &MockAgentApp{ctrl: ctrl}
	mock.recorder = &MockAgentAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentApp) EXPECT() *MockAgentAppMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockAgentApp) Acquire() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Acquire indicates an expected call of Acquire.
func (mr *MockAgentAppMockRecorder) Acquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockAgentApp)(nil).Acquire))
}

// AuthUser mocks base method.
func (m *MockAgentApp) AuthUser(token string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", token)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockAgentAppMockRecorder) AuthUser(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockAgentApp)(nil).AuthUser), token)
}

// BeforeStart mocks base method.
func (m *MockAgentApp) BeforeStart(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStart", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStart indicates an expected call of BeforeStart.
func (mr *MockAgentAppMockRecorder) BeforeStart(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStart", reflect.TypeOf((*MockAgentApp)(nil).BeforeStart), arg0)
}

// BeforeStop mocks base method.
func (m *MockAgentApp) BeforeStop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStop indicates an expected call of BeforeStop.
func (mr *MockAgentAppMockRecorder) BeforeStop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStop", reflect.TypeOf((*MockAgentApp)(nil).BeforeStop), arg0)
}

// CheckUserPlan mocks base method.
func (m *MockAgentApp) CheckUserPlan(arg0 core.AgentConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPlan", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// CheckUserPlan indicates an expected call of CheckUserPlan.
func (mr *MockAgentAppMockRecorder) CheckUserPlan(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPlan", reflect.TypeOf((*MockAgentApp)(nil).CheckUserPlan), arg0)
}

// CloseBenchmarkListeningChannels mocks base method.
func (m *MockAgentApp) CloseBenchmarkListeningChannels() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseBenchmarkListeningChannels")
}

// CloseBenchmarkListeningChannels indicates an expected call of CloseBenchmarkListeningChannels.
func (mr *MockAgentAppMockRecorder) CloseBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseBenchmarkListeningChannels", reflect.TypeOf((*MockAgentApp)(nil).CloseBenchmarkListeningChannels))
}

// GetBenchmarkListeningChannels mocks base method.
func (m *MockAgentApp) GetBenchmarkListeningChannels() map[string]chan core.StatEvent[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBenchmarkListeningChannels")
	ret0, _ := ret[0].(map[string]chan core.StatEvent[any])
	return ret0
}

// GetBenchmarkListeningChannels indicates an expected call of GetBenchmarkListeningChannels.
func (mr *MockAgentAppMockRecorder) GetBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBenchmarkListeningChannels", reflect.TypeOf((*MockAgentApp)(nil).GetBenchmarkListeningChannels))
}

// auto-added: GetAgentCore mocks base method.
func (m *MockAgentApp) GetAgentCore() core.AgentCore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCore")
	ret0, _ := ret[0].(core.AgentCore)
	return ret0
}

// auto-added: GetAgentCore indicates an expected call of GetAgentCore.
func (mr *MockAgentAppMockRecorder) GetAgentCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCore", reflect.TypeOf((*MockAgentApp)(nil).GetAgentCore))
}

// auto-added: GetAppConfig mocks base method.
func (m *MockAgentApp) GetAppConfig() core.AppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppConfig")
	ret0, _ := ret[0].(core.AppConfig)
	return ret0
}

// auto-added: GetAppConfig indicates an expected call of GetAppConfig.
func (mr *MockAgentAppMockRecorder) GetAppConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppConfig", reflect.TypeOf((*MockAgentApp)(nil).GetAppConfig))
}

// GetConfigPath mocks base method.
func (m *MockAgentApp) GetConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockAgentAppMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockAgentApp)(nil).GetConfigPath))
}

// GetEventChans mocks base method.
func (m *MockAgentApp) GetEventChans() map[string]chan core.Event[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventChans")
	ret0, _ := ret[0].(map[string]chan core.Event[any])
	return ret0
}

// GetEventChans indicates an expected call of GetEventChans.
func (mr *MockAgentAppMockRecorder) GetEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventChans", reflect.TypeOf((*MockAgentApp)(nil).GetEventChans))
}

// GetHistory mocks base method.
func (m *MockAgentApp) GetHistory() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockAgentAppMockRecorder) GetHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockAgentApp)(nil).GetHistory))
}

// GetID mocks base method.
func (m *MockAgentApp) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAgentAppMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAgentApp)(nil).GetID))
}

// GetKnowledgeBase mocks base method.
func (m *MockAgentApp) GetKnowledgeBase() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockAgentAppMockRecorder) GetKnowledgeBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockAgentApp)(nil).GetKnowledgeBase))
}

// auto-added: GetLogger mocks base method.
func (m *MockAgentApp) GetLogger() *log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*log.Logger)
	return ret0
}

// auto-added: GetLogger indicates an expected call of GetLogger.
func (mr *MockAgentAppMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockAgentApp)(nil).GetLogger))
}

// GetModelProviders mocks base method.
func (m *MockAgentApp) GetModelProviders() []core.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProviders")
	ret0, _ := ret[0].([]core.Provider)
	return ret0
}

// GetModelProviders indicates an expected call of GetModelProviders.
func (mr *MockAgentAppMockRecorder) GetModelProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProviders", reflect.TypeOf((*MockAgentApp)(nil).GetModelProviders))
}

// GetPrompt mocks base method.
func (m *MockAgentApp) GetPrompt() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockAgentAppMockRecorder) GetPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockAgentApp)(nil).GetPrompt))
}

// GetSessionConfig mocks base method.
func (m *MockAgentApp) GetSessionConfig() core.SessionConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionConfig")
	ret0, _ := ret[0].(core.SessionConfig)
	return ret0
}

// GetSessionConfig indicates an expected call of GetSessionConfig.
func (mr *MockAgentAppMockRecorder) GetSessionConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionConfig", reflect.TypeOf((*MockAgentApp)(nil).GetSessionConfig))
}

// GetSessionOnCreate mocks base method.
func (m *MockAgentApp) GetSessionOnCreate(arg0 string, arg1 bool) (core.Session, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionOnCreate", arg0, arg1)
	ret0, _ := ret[0].(core.Session)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// GetSessionOnCreate indicates an expected call of GetSessionOnCreate.
func (mr *MockAgentAppMockRecorder) GetSessionOnCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionOnCreate", reflect.TypeOf((*MockAgentApp)(nil).GetSessionOnCreate), arg0, arg1)
}

// GetSkills mocks base method.
func (m *MockAgentApp) GetSkills() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkills")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetSkills indicates an expected call of GetSkills.
func (mr *MockAgentAppMockRecorder) GetSkills() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkills", reflect.TypeOf((*MockAgentApp)(nil).GetSkills))
}

// GetToolsConfig mocks base method.
func (m *MockAgentApp) GetToolsConfig() []core.ToolConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolsConfig")
	ret0, _ := ret[0].([]core.ToolConfig)
	return ret0
}

// GetToolsConfig indicates an expected call of GetToolsConfig.
func (mr *MockAgentAppMockRecorder) GetToolsConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolsConfig", reflect.TypeOf((*MockAgentApp)(nil).GetToolsConfig))
}

// GetUserInput mocks base method.
func (m *MockAgentApp) GetUserInput() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInput")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserInput indicates an expected call of GetUserInput.
func (mr *MockAgentAppMockRecorder) GetUserInput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInput", reflect.TypeOf((*MockAgentApp)(nil).GetUserInput))
}

// auto-added: GracefulQuit mocks base method.
func (m *MockAgentApp) GracefulQuit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulQuit")
}

// auto-added: GracefulQuit indicates an expected call of GracefulQuit.
func (mr *MockAgentAppMockRecorder) GracefulQuit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulQuit", reflect.TypeOf((*MockAgentApp)(nil).GracefulQuit))
}

// LoadAppConfig mocks base method.
func (m *MockAgentApp) LoadAppConfig(path string) core.AppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAppConfig", path)
	ret0, _ := ret[0].(core.AppConfig)
	return ret0
}

// LoadAppConfig indicates an expected call of LoadAppConfig.
func (mr *MockAgentAppMockRecorder) LoadAppConfig(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAppConfig", reflect.TypeOf((*MockAgentApp)(nil).LoadAppConfig), path)
}

// LoadConfigs mocks base method.
func (m *MockAgentApp) LoadConfigs(path string) (core.AgentCoreConfig, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigs", path)
	ret0, _ := ret[0].(core.AgentCoreConfig)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// LoadConfigs indicates an expected call of LoadConfigs.
func (mr *MockAgentAppMockRecorder) LoadConfigs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigs", reflect.TypeOf((*MockAgentApp)(nil).LoadConfigs), path)
}

// OnEvent mocks base method.
func (m *MockAgentApp) OnEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEvent")
}

// OnEvent indicates an expected call of OnEvent.
func (mr *MockAgentAppMockRecorder) OnEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEvent", reflect.TypeOf((*MockAgentApp)(nil).OnEvent))
}

// RegisterEventChans mocks base method.
func (m *MockAgentApp) RegisterEventChans() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEventChans")
}

// RegisterEventChans indicates an expected call of RegisterEventChans.
func (mr *MockAgentAppMockRecorder) RegisterEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventChans", reflect.TypeOf((*MockAgentApp)(nil).RegisterEventChans))
}

// Release mocks base method.
func (m *MockAgentApp) Release() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockAgentAppMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAgentApp)(nil).Release))
}

// Render mocks base method.
func (m *MockAgentApp) Render(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Render", arg0)
}

// Render indicates an expected call of Render.
func (mr *MockAgentAppMockRecorder) Render(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockAgentApp)(nil).Render), arg0)
}

// RenderSystemMessage mocks base method.
func (m *MockAgentApp) RenderSystemMessage(arg0 []core.Diagnostic) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderSystemMessage", arg0)
}

// RenderSystemMessage indicates an expected call of RenderSystemMessage.
func (mr *MockAgentAppMockRecorder) RenderSystemMessage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderSystemMessage", reflect.TypeOf((*MockAgentApp)(nil).RenderSystemMessage), arg0)
}

// auto-added: SetAgentCore mocks base method.
func (m *MockAgentApp) SetAgentCore(arg0 core.AgentCore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAgentCore", arg0)
}

// auto-added: SetAgentCore indicates an expected call of SetAgentCore.
func (mr *MockAgentAppMockRecorder) SetAgentCore(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentCore", reflect.TypeOf((*MockAgentApp)(nil).SetAgentCore), arg0)
}

// auto-added: SetAppConfig mocks base method.
func (m *MockAgentApp) SetAppConfig(arg0 core.AppConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppConfig", arg0)
}

// auto-added: SetAppConfig indicates an expected call of SetAppConfig.
func (mr *MockAgentAppMockRecorder) SetAppConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppConfig", reflect.TypeOf((*MockAgentApp)(nil).SetAppConfig), arg0)
}

// SetConfig mocks base method.
func (m *MockAgentApp) SetConfig(config core.I18nConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConfig", config)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockAgentAppMockRecorder) SetConfig(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockAgentApp)(nil).SetConfig), config)
}

// SetHistory mocks base method.
func (m *MockAgentApp) SetHistory(arg0 core.HistoryConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockAgentAppMockRecorder) SetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockAgentApp)(nil).SetHistory), arg0)
}

// SetID mocks base method.
func (m *MockAgentApp) SetID() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetID")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetID indicates an expected call of SetID.
func (mr *MockAgentAppMockRecorder) SetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockAgentApp)(nil).SetID))
}

// SetKnowledgeBase mocks base method.
func (m *MockAgentApp) SetKnowledgeBase(arg0 core.KnowledgeBaseConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKnowledgeBase", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetKnowledgeBase indicates an expected call of SetKnowledgeBase.
func (mr *MockAgentAppMockRecorder) SetKnowledgeBase(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKnowledgeBase", reflect.TypeOf((*MockAgentApp)(nil).SetKnowledgeBase), arg0)
}

// SetLanguage mocks base method.
func (m *MockAgentApp) SetLanguage(arg0 core.LanguageType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLanguage", arg0)
}

// SetLanguage indicates an expected call of SetLanguage.
func (mr *MockAgentAppMockRecorder) SetLanguage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLanguage", reflect.TypeOf((*MockAgentApp)(nil).SetLanguage), arg0)
}

// auto-added: SetLogger mocks base method.
func (m *MockAgentApp) SetLogger(arg0 *log.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", arg0)
}

// auto-added: SetLogger indicates an expected call of SetLogger.
func (mr *MockAgentAppMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockAgentApp)(nil).SetLogger), arg0)
}

// SetModelProviders mocks base method.
func (m *MockAgentApp) SetModelProviders(modelConfigs []core.ModelConfig, appConfig core.AppConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModelProviders", modelConfigs, appConfig)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetModelProviders indicates an expected call of SetModelProviders.
func (mr *MockAgentAppMockRecorder) SetModelProviders(modelConfigs, appConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModelProviders", reflect.TypeOf((*MockAgentApp)(nil).SetModelProviders), modelConfigs, appConfig)
}

// SetPrompt mocks base method.
func (m *MockAgentApp) SetPrompt(arg0 core.PromptConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrompt", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetPrompt indicates an expected call of SetPrompt.
func (mr *MockAgentAppMockRecorder) SetPrompt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrompt", reflect.TypeOf((*MockAgentApp)(nil).SetPrompt), arg0)
}

// auto-added: SetRouter mocks base method.
func (m *MockAgentApp) SetRouter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRouter")
}

// auto-added: SetRouter indicates an expected call of SetRouter.
func (mr *MockAgentAppMockRecorder) SetRouter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRouter", reflect.TypeOf((*MockAgentApp)(nil).SetRouter))
}

// SetSkills mocks base method.
func (m *MockAgentApp) SetSkills(arg0 core.SkillConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSkills", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetSkills indicates an expected call of SetSkills.
func (mr *MockAgentAppMockRecorder) SetSkills(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSkills", reflect.TypeOf((*MockAgentApp)(nil).SetSkills), arg0)
}

// auto-added: Start mocks base method.
func (m *MockAgentApp) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// auto-added: Start indicates an expected call of Start.
func (mr *MockAgentAppMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAgentApp)(nil).Start))
}

// auto-added: Stop mocks base method.
func (m *MockAgentApp) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// auto-added: Stop indicates an expected call of Stop.
func (mr *MockAgentAppMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAgentApp)(nil).Stop))
}

// StopSession mocks base method.
func (m *MockAgentApp) StopSession(arg0 string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSession", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// StopSession indicates an expected call of StopSession.
func (mr *MockAgentAppMockRecorder) StopSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSession", reflect.TypeOf((*MockAgentApp)(nil).StopSession), arg0)
}

// Translate mocks base method.
func (m *MockAgentApp) Translate(key string, targetLanguage core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", key, targetLanguage)
	ret0, _ := ret[0].(string)
	return ret0
}

// Translate indicates an expected call of Translate.
func (mr *MockAgentAppMockRecorder) Translate(key, targetLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockAgentApp)(nil).Translate), key, targetLanguage)
}

// Welcome mocks base method.
func (m *MockAgentApp) Welcome() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Welcome")
}

// Welcome indicates an expected call of Welcome.
func (mr *MockAgentAppMockRecorder) Welcome() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Welcome", reflect.TypeOf((*MockAgentApp)(nil).Welcome))
}
