// Code generated by MockGen. DO NOT EDIT.
// Source: core/event.go
//
// Generated by this command:
//
//	mockgen -source=core/event.go -destination=test/mock/mock_event.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockEvent is a mock of Event interface.
type MockEvent[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockEventMockRecorder[T]
	isgomock struct{}
}

// MockEventMockRecorder is the mock recorder for MockEvent.
type MockEventMockRecorder[T any] struct {
	mock *MockEvent[T]
}

// NewMockEvent creates a new mock instance.
func NewMockEvent[T any](ctrl *gomock.Controller) *MockEvent[T] {
	mock := &MockEvent[T]{ctrl: ctrl}
	mock.recorder = &MockEventMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvent[T]) EXPECT() *MockEventMockRecorder[T] {
	return m.recorder
}

// GetData mocks base method.
func (m *MockEvent[T]) GetData() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData")
	ret0, _ := ret[0].(T)
	return ret0
}

// GetData indicates an expected call of GetData.
func (mr *MockEventMockRecorder[T]) GetData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockEvent[T])(nil).GetData))
}

// GetSourceType mocks base method.
func (m *MockEvent[T]) GetSourceType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSourceType indicates an expected call of GetSourceType.
func (mr *MockEventMockRecorder[T]) GetSourceType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceType", reflect.TypeOf((*MockEvent[T])(nil).GetSourceType))
}

// ToString mocks base method.
func (m *MockEvent[T]) ToString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockEventMockRecorder[T]) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockEvent[T])(nil).ToString))
}

// WriteToStorage mocks base method.
func (m *MockEvent[T]) WriteToStorage() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteToStorage")
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteToStorage indicates an expected call of WriteToStorage.
func (mr *MockEventMockRecorder[T]) WriteToStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteToStorage", reflect.TypeOf((*MockEvent[T])(nil).WriteToStorage))
}

// MockEventManager is a mock of EventManager interface.
type MockEventManager struct {
	ctrl     *gomock.Controller
	recorder *MockEventManagerMockRecorder
	isgomock struct{}
}

// MockEventManagerMockRecorder is the mock recorder for MockEventManager.
type MockEventManagerMockRecorder struct {
	mock *MockEventManager
}

// NewMockEventManager creates a new mock instance.
func NewMockEventManager(ctrl *gomock.Controller) *MockEventManager {
	mock := &MockEventManager{ctrl: ctrl}
	mock.recorder = &MockEventManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventManager) EXPECT() *MockEventManagerMockRecorder {
	return m.recorder
}

// GetEventChans mocks base method.
func (m *MockEventManager) GetEventChans() map[string]chan core.Event[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventChans")
	ret0, _ := ret[0].(map[string]chan core.Event[any])
	return ret0
}

// GetEventChans indicates an expected call of GetEventChans.
func (mr *MockEventManagerMockRecorder) GetEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventChans", reflect.TypeOf((*MockEventManager)(nil).GetEventChans))
}

// OnEvent mocks base method.
func (m *MockEventManager) OnEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEvent")
}

// OnEvent indicates an expected call of OnEvent.
func (mr *MockEventManagerMockRecorder) OnEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEvent", reflect.TypeOf((*MockEventManager)(nil).OnEvent))
}

// RegisterEventChans mocks base method.
func (m *MockEventManager) RegisterEventChans() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEventChans")
}

// RegisterEventChans indicates an expected call of RegisterEventChans.
func (mr *MockEventManagerMockRecorder) RegisterEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventChans", reflect.TypeOf((*MockEventManager)(nil).RegisterEventChans))
}
