// Code generated by MockGen. DO NOT EDIT.
// Source: core/sandbox.go
//
// Generated by this command:
//
//	mockgen -source=core/sandbox.go -destination=test/mock/mock_sandbox.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockSandbox is a mock of Sandbox interface.
type MockSandbox struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxMockRecorder
	isgomock struct{}
}

// MockSandboxMockRecorder is the mock recorder for MockSandbox.
type MockSandboxMockRecorder struct {
	mock *MockSandbox
}

// NewMockSandbox creates a new mock instance.
func NewMockSandbox(ctrl *gomock.Controller) *MockSandbox {
	mock := &MockSandbox{ctrl: ctrl}
	mock.recorder = &MockSandboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSandbox) EXPECT() *MockSandboxMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockSandbox) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockSandboxMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockSandbox)(nil).Connect))
}

// DryRun mocks base method.
func (m *MockSandbox) DryRun(tool core.Tool, args map[string]any) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DryRun", tool, args)
	ret0, _ := ret[0].(string)
	return ret0
}

// DryRun indicates an expected call of DryRun.
func (mr *MockSandboxMockRecorder) DryRun(tool, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DryRun", reflect.TypeOf((*MockSandbox)(nil).DryRun), tool, args)
}

// Run mocks base method.
func (m *MockSandbox) Run(tool core.Tool, args map[string]any) (string, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", tool, args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockSandboxMockRecorder) Run(tool, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSandbox)(nil).Run), tool, args)
}

// WithStub mocks base method.
func (m *MockSandbox) WithStub(stub []string) core.Sandbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithStub", stub)
	ret0, _ := ret[0].(core.Sandbox)
	return ret0
}

// WithStub indicates an expected call of WithStub.
func (mr *MockSandboxMockRecorder) WithStub(stub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithStub", reflect.TypeOf((*MockSandbox)(nil).WithStub), stub)
}
