// Code generated by MockGen. DO NOT EDIT.
// Source: core/kb.go
//
// Generated by this command:
//
//	mockgen -source=core/kb.go -destination=test/mock/mock_kb.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockDocLoader is a mock of DocLoader interface.
type MockDocLoader struct {
	ctrl     *gomock.Controller
	recorder *MockDocLoaderMockRecorder
	isgomock struct{}
}

// MockDocLoaderMockRecorder is the mock recorder for MockDocLoader.
type MockDocLoaderMockRecorder struct {
	mock *MockDocLoader
}

// NewMockDocLoader creates a new mock instance.
func NewMockDocLoader(ctrl *gomock.Controller) *MockDocLoader {
	mock := &MockDocLoader{ctrl: ctrl}
	mock.recorder = &MockDocLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocLoader) EXPECT() *MockDocLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockDocLoader) Load(data []byte, filename string) (string, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", data, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockDocLoaderMockRecorder) Load(data, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockDocLoader)(nil).Load), data, filename)
}

// SupportedExtensions mocks base method.
func (m *MockDocLoader) SupportedExtensions() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedExtensions")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SupportedExtensions indicates an expected call of SupportedExtensions.
func (mr *MockDocLoaderMockRecorder) SupportedExtensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedExtensions", reflect.TypeOf((*MockDocLoader)(nil).SupportedExtensions))
}

// MockChunker is a mock of Chunker interface.
type MockChunker struct {
	ctrl     *gomock.Controller
	recorder *MockChunkerMockRecorder
	isgomock struct{}
}

// MockChunkerMockRecorder is the mock recorder for MockChunker.
type MockChunkerMockRecorder struct {
	mock *MockChunker
}

// NewMockChunker creates a new mock instance.
func NewMockChunker(ctrl *gomock.Controller) *MockChunker {
	mock := &MockChunker{ctrl: ctrl}
	mock.recorder = &MockChunkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunker) EXPECT() *MockChunkerMockRecorder {
	return m.recorder
}

// Chunk mocks base method.
func (m *MockChunker) Chunk(content string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chunk", content)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Chunk indicates an expected call of Chunk.
func (mr *MockChunkerMockRecorder) Chunk(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chunk", reflect.TypeOf((*MockChunker)(nil).Chunk), content)
}

// SupportedTypes mocks base method.
func (m *MockChunker) SupportedTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SupportedTypes indicates an expected call of SupportedTypes.
func (mr *MockChunkerMockRecorder) SupportedTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedTypes", reflect.TypeOf((*MockChunker)(nil).SupportedTypes))
}

// MockEmbedder is a mock of Embedder interface.
type MockEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderMockRecorder
	isgomock struct{}
}

// MockEmbedderMockRecorder is the mock recorder for MockEmbedder.
type MockEmbedderMockRecorder struct {
	mock *MockEmbedder
}

// NewMockEmbedder creates a new mock instance.
func NewMockEmbedder(ctrl *gomock.Controller) *MockEmbedder {
	mock := &MockEmbedder{ctrl: ctrl}
	mock.recorder = &MockEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedder) EXPECT() *MockEmbedderMockRecorder {
	return m.recorder
}

// Embed mocks base method.
func (m *MockEmbedder) Embed(data any) (*core.EmbeddingResult, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", data)
	ret0, _ := ret[0].(*core.EmbeddingResult)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockEmbedderMockRecorder) Embed(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockEmbedder)(nil).Embed), data)
}

// MockKnowledgeBase is a mock of KnowledgeBase interface.
type MockKnowledgeBase[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockKnowledgeBaseMockRecorder[T]
	isgomock struct{}
}

// MockKnowledgeBaseMockRecorder is the mock recorder for MockKnowledgeBase.
type MockKnowledgeBaseMockRecorder[T any] struct {
	mock *MockKnowledgeBase[T]
}

// NewMockKnowledgeBase creates a new mock instance.
func NewMockKnowledgeBase[T any](ctrl *gomock.Controller) *MockKnowledgeBase[T] {
	mock := &MockKnowledgeBase[T]{ctrl: ctrl}
	mock.recorder = &MockKnowledgeBaseMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKnowledgeBase[T]) EXPECT() *MockKnowledgeBaseMockRecorder[T] {
	return m.recorder
}

// GetEmedder mocks base method.
func (m *MockKnowledgeBase[T]) GetEmedder() core.Embedder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmedder")
	ret0, _ := ret[0].(core.Embedder)
	return ret0
}

// GetEmedder indicates an expected call of GetEmedder.
func (mr *MockKnowledgeBaseMockRecorder[T]) GetEmedder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmedder", reflect.TypeOf((*MockKnowledgeBase[T])(nil).GetEmedder))
}

// Process mocks base method.
func (m *MockKnowledgeBase[T]) Process(data []byte, filename string) (*core.EmbeddingResult, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", data, filename)
	ret0, _ := ret[0].(*core.EmbeddingResult)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockKnowledgeBaseMockRecorder[T]) Process(data, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockKnowledgeBase[T])(nil).Process), data, filename)
}

// Save mocks base method.
func (m *MockKnowledgeBase[T]) Save(entities []T) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", entities)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockKnowledgeBaseMockRecorder[T]) Save(entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockKnowledgeBase[T])(nil).Save), entities)
}

// Search mocks base method.
func (m *MockKnowledgeBase[T]) Search(keyword any, topK int, filter string) ([]core.Readable, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", keyword, topK, filter)
	ret0, _ := ret[0].([]core.Readable)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockKnowledgeBaseMockRecorder[T]) Search(keyword, topK, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockKnowledgeBase[T])(nil).Search), keyword, topK, filter)
}

// MockReadable is a mock of Readable interface.
type MockReadable struct {
	ctrl     *gomock.Controller
	recorder *MockReadableMockRecorder
	isgomock struct{}
}

// MockReadableMockRecorder is the mock recorder for MockReadable.
type MockReadableMockRecorder struct {
	mock *MockReadable
}

// NewMockReadable creates a new mock instance.
func NewMockReadable(ctrl *gomock.Controller) *MockReadable {
	mock := &MockReadable{ctrl: ctrl}
	mock.recorder = &MockReadableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadable) EXPECT() *MockReadableMockRecorder {
	return m.recorder
}

// GetConfidence mocks base method.
func (m *MockReadable) GetConfidence() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfidence")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetConfidence indicates an expected call of GetConfidence.
func (mr *MockReadableMockRecorder) GetConfidence() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfidence", reflect.TypeOf((*MockReadable)(nil).GetConfidence))
}

// GetContent mocks base method.
func (m *MockReadable) GetContent() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetContent indicates an expected call of GetContent.
func (mr *MockReadableMockRecorder) GetContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockReadable)(nil).GetContent))
}
