// Code generated by MockGen. DO NOT EDIT.
// Source: core/command.go
//
// Generated by this command:
//
//	mockgen -source=core/command.go -destination=test/mock/mock_command.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// GetBase mocks base method.
func (m *MockCommand) GetBase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBase indicates an expected call of GetBase.
func (mr *MockCommandMockRecorder) GetBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBase", reflect.TypeOf((*MockCommand)(nil).GetBase))
}

// GetHelp mocks base method.
func (m *MockCommand) GetHelp() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelp")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetHelp indicates an expected call of GetHelp.
func (mr *MockCommandMockRecorder) GetHelp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelp", reflect.TypeOf((*MockCommand)(nil).GetHelp))
}

// GetOutputChans mocks base method.
func (m *MockCommand) GetOutputChans() []core.OutputChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutputChans")
	ret0, _ := ret[0].([]core.OutputChannel)
	return ret0
}

// GetOutputChans indicates an expected call of GetOutputChans.
func (mr *MockCommandMockRecorder) GetOutputChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutputChans", reflect.TypeOf((*MockCommand)(nil).GetOutputChans))
}

// Run mocks base method.
func (m *MockCommand) Run(app core.CommandApp) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", app)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCommandMockRecorder) Run(app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommand)(nil).Run), app)
}

// WithOption mocks base method.
func (m *MockCommand) WithOption(arg0, arg1 string) core.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithOption", arg0, arg1)
	ret0, _ := ret[0].(core.Command)
	return ret0
}

// WithOption indicates an expected call of WithOption.
func (mr *MockCommandMockRecorder) WithOption(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithOption", reflect.TypeOf((*MockCommand)(nil).WithOption), arg0, arg1)
}

// MockCommandParser is a mock of CommandParser interface.
type MockCommandParser struct {
	ctrl     *gomock.Controller
	recorder *MockCommandParserMockRecorder
	isgomock struct{}
}

// MockCommandParserMockRecorder is the mock recorder for MockCommandParser.
type MockCommandParserMockRecorder struct {
	mock *MockCommandParser
}

// NewMockCommandParser creates a new mock instance.
func NewMockCommandParser(ctrl *gomock.Controller) *MockCommandParser {
	mock := &MockCommandParser{ctrl: ctrl}
	mock.recorder = &MockCommandParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandParser) EXPECT() *MockCommandParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockCommandParser) Parse(arg0 string) (core.Command, []core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", arg0)
	ret0, _ := ret[0].(core.Command)
	ret1, _ := ret[1].([]core.Diagnostic)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockCommandParserMockRecorder) Parse(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockCommandParser)(nil).Parse), arg0)
}

// MockCommandApp is a mock of CommandApp interface.
type MockCommandApp struct {
	ctrl     *gomock.Controller
	recorder *MockCommandAppMockRecorder
	isgomock struct{}
}

// MockCommandAppMockRecorder is the mock recorder for MockCommandApp.
type MockCommandAppMockRecorder struct {
	mock *MockCommandApp
}

// NewMockCommandApp creates a new mock instance.
func NewMockCommandApp(ctrl *gomock.Controller) *MockCommandApp {
	mock := &MockCommandApp{ctrl: ctrl}
	mock.recorder = &MockCommandAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandApp) EXPECT() *MockCommandAppMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockCommandApp) AuthUser(token string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", token)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockCommandAppMockRecorder) AuthUser(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockCommandApp)(nil).AuthUser), token)
}

// BeforeStart mocks base method.
func (m *MockCommandApp) BeforeStart() []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStart")
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStart indicates an expected call of BeforeStart.
func (mr *MockCommandAppMockRecorder) BeforeStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStart", reflect.TypeOf((*MockCommandApp)(nil).BeforeStart))
}

// BeforeStop mocks base method.
func (m *MockCommandApp) BeforeStop() []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStop")
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStop indicates an expected call of BeforeStop.
func (mr *MockCommandAppMockRecorder) BeforeStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStop", reflect.TypeOf((*MockCommandApp)(nil).BeforeStop))
}

// CheckUserPlan mocks base method.
func (m *MockCommandApp) CheckUserPlan(userInfo any, plan core.Plan) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPlan", userInfo, plan)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// CheckUserPlan indicates an expected call of CheckUserPlan.
func (mr *MockCommandAppMockRecorder) CheckUserPlan(userInfo, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPlan", reflect.TypeOf((*MockCommandApp)(nil).CheckUserPlan), userInfo, plan)
}

// GetAgentCore mocks base method.
func (m *MockCommandApp) GetAgentCore() *core.AgentCore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCore")
	ret0, _ := ret[0].(*core.AgentCore)
	return ret0
}

// GetAgentCore indicates an expected call of GetAgentCore.
func (mr *MockCommandAppMockRecorder) GetAgentCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCore", reflect.TypeOf((*MockCommandApp)(nil).GetAgentCore))
}

// GetConfig mocks base method.
func (m *MockCommandApp) GetConfig() core.CommandAppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(core.CommandAppConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockCommandAppMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockCommandApp)(nil).GetConfig))
}

// GetHelpDoc mocks base method.
func (m *MockCommandApp) GetHelpDoc() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelpDoc")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHelpDoc indicates an expected call of GetHelpDoc.
func (mr *MockCommandAppMockRecorder) GetHelpDoc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelpDoc", reflect.TypeOf((*MockCommandApp)(nil).GetHelpDoc))
}

// GetUserInput mocks base method.
func (m *MockCommandApp) GetUserInput() chan core.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInput")
	ret0, _ := ret[0].(chan core.Command)
	return ret0
}

// GetUserInput indicates an expected call of GetUserInput.
func (mr *MockCommandAppMockRecorder) GetUserInput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInput", reflect.TypeOf((*MockCommandApp)(nil).GetUserInput))
}

// GetUserPlan mocks base method.
func (m *MockCommandApp) GetUserPlan(userID string) (core.Plan, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPlan", userID)
	ret0, _ := ret[0].(core.Plan)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// GetUserPlan indicates an expected call of GetUserPlan.
func (mr *MockCommandAppMockRecorder) GetUserPlan(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPlan", reflect.TypeOf((*MockCommandApp)(nil).GetUserPlan), userID)
}

// GracefulQuit mocks base method.
func (m *MockCommandApp) GracefulQuit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulQuit")
}

// GracefulQuit indicates an expected call of GracefulQuit.
func (mr *MockCommandAppMockRecorder) GracefulQuit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulQuit", reflect.TypeOf((*MockCommandApp)(nil).GracefulQuit))
}

// Parse mocks base method.
func (m *MockCommandApp) Parse(arg0 string) (core.Command, []core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", arg0)
	ret0, _ := ret[0].(core.Command)
	ret1, _ := ret[1].([]core.Diagnostic)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockCommandAppMockRecorder) Parse(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockCommandApp)(nil).Parse), arg0)
}

// Render mocks base method.
func (m *MockCommandApp) Render(arg0 core.MessageCode, arg1 core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockCommandAppMockRecorder) Render(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockCommandApp)(nil).Render), arg0, arg1)
}

// RenderSystemMessage mocks base method.
func (m *MockCommandApp) RenderSystemMessage(arg0 *core.DiagnosticList, arg1 core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderSystemMessage", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// RenderSystemMessage indicates an expected call of RenderSystemMessage.
func (mr *MockCommandAppMockRecorder) RenderSystemMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderSystemMessage", reflect.TypeOf((*MockCommandApp)(nil).RenderSystemMessage), arg0, arg1)
}

// Start mocks base method.
func (m *MockCommandApp) Start() []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCommandAppMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCommandApp)(nil).Start))
}

// Stop mocks base method.
func (m *MockCommandApp) Stop() []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockCommandAppMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCommandApp)(nil).Stop))
}

// Translate mocks base method.
func (m *MockCommandApp) Translate(key core.MessageCode, targetLanguage core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", key, targetLanguage)
	ret0, _ := ret[0].(string)
	return ret0
}

// Translate indicates an expected call of Translate.
func (mr *MockCommandAppMockRecorder) Translate(key, targetLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockCommandApp)(nil).Translate), key, targetLanguage)
}

// Welcome mocks base method.
func (m *MockCommandApp) Welcome() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Welcome")
	ret0, _ := ret[0].(string)
	return ret0
}

// Welcome indicates an expected call of Welcome.
func (mr *MockCommandAppMockRecorder) Welcome() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Welcome", reflect.TypeOf((*MockCommandApp)(nil).Welcome))
}
