// Code generated by MockGen. DO NOT EDIT.
// Source: core/agent.go
//
// Generated by this command:
//
//	mockgen -source=core/agent.go -destination=test/mock_agent.go -package=test
//

// Package test is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockLockManager is a mock of LockManager interface.
type MockLockManager struct {
	ctrl     *gomock.Controller
	recorder *MockLockManagerMockRecorder
	isgomock struct{}
}

// MockLockManagerMockRecorder is the mock recorder for MockLockManager.
type MockLockManagerMockRecorder struct {
	mock *MockLockManager
}

// NewMockLockManager creates a new mock instance.
func NewMockLockManager(ctrl *gomock.Controller) *MockLockManager {
	mock := &MockLockManager{ctrl: ctrl}
	mock.recorder = &MockLockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLockManager) EXPECT() *MockLockManagerMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockLockManager) Acquire() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Acquire indicates an expected call of Acquire.
func (mr *MockLockManagerMockRecorder) Acquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockLockManager)(nil).Acquire))
}

// Release mocks base method.
func (m *MockLockManager) Release() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockLockManagerMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockLockManager)(nil).Release))
}

// MockUI is a mock of UI interface.
type MockUI struct {
	ctrl     *gomock.Controller
	recorder *MockUIMockRecorder
	isgomock struct{}
}

// MockUIMockRecorder is the mock recorder for MockUI.
type MockUIMockRecorder struct {
	mock *MockUI
}

// NewMockUI creates a new mock instance.
func NewMockUI(ctrl *gomock.Controller) *MockUI {
	mock := &MockUI{ctrl: ctrl}
	mock.recorder = &MockUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUI) EXPECT() *MockUIMockRecorder {
	return m.recorder
}

// GetUserInput mocks base method.
func (m *MockUI) GetUserInput() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInput")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserInput indicates an expected call of GetUserInput.
func (mr *MockUIMockRecorder) GetUserInput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInput", reflect.TypeOf((*MockUI)(nil).GetUserInput))
}

// Render mocks base method.
func (m *MockUI) Render(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Render", arg0)
}

// Render indicates an expected call of Render.
func (mr *MockUIMockRecorder) Render(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockUI)(nil).Render), arg0)
}

// RenderSystemMessage mocks base method.
func (m *MockUI) RenderSystemMessage(arg0 []core.Diagnostic) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderSystemMessage", arg0)
}

// RenderSystemMessage indicates an expected call of RenderSystemMessage.
func (mr *MockUIMockRecorder) RenderSystemMessage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderSystemMessage", reflect.TypeOf((*MockUI)(nil).RenderSystemMessage), arg0)
}

// Welcome mocks base method.
func (m *MockUI) Welcome() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Welcome")
}

// Welcome indicates an expected call of Welcome.
func (mr *MockUIMockRecorder) Welcome() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Welcome", reflect.TypeOf((*MockUI)(nil).Welcome))
}

// MockConfigure is a mock of Configure interface.
type MockConfigure struct {
	ctrl     *gomock.Controller
	recorder *MockConfigureMockRecorder
	isgomock struct{}
}

// MockConfigureMockRecorder is the mock recorder for MockConfigure.
type MockConfigureMockRecorder struct {
	mock *MockConfigure
}

// NewMockConfigure creates a new mock instance.
func NewMockConfigure(ctrl *gomock.Controller) *MockConfigure {
	mock := &MockConfigure{ctrl: ctrl}
	mock.recorder = &MockConfigureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigure) EXPECT() *MockConfigureMockRecorder {
	return m.recorder
}

// GetConfigPath mocks base method.
func (m *MockConfigure) GetConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockConfigureMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockConfigure)(nil).GetConfigPath))
}

// MockWorkFlow is a mock of WorkFlow interface.
type MockWorkFlow struct {
	ctrl     *gomock.Controller
	recorder *MockWorkFlowMockRecorder
	isgomock struct{}
}

// MockWorkFlowMockRecorder is the mock recorder for MockWorkFlow.
type MockWorkFlowMockRecorder struct {
	mock *MockWorkFlow
}

// NewMockWorkFlow creates a new mock instance.
func NewMockWorkFlow(ctrl *gomock.Controller) *MockWorkFlow {
	mock := &MockWorkFlow{ctrl: ctrl}
	mock.recorder = &MockWorkFlowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkFlow) EXPECT() *MockWorkFlowMockRecorder {
	return m.recorder
}

// BeforeStart mocks base method.
func (m *MockWorkFlow) BeforeStart(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStart", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStart indicates an expected call of BeforeStart.
func (mr *MockWorkFlowMockRecorder) BeforeStart(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStart", reflect.TypeOf((*MockWorkFlow)(nil).BeforeStart), arg0)
}

// BeforeStop mocks base method.
func (m *MockWorkFlow) BeforeStop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStop indicates an expected call of BeforeStop.
func (mr *MockWorkFlowMockRecorder) BeforeStop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStop", reflect.TypeOf((*MockWorkFlow)(nil).BeforeStop), arg0)
}

// Start mocks base method.
func (m *MockWorkFlow) Start(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWorkFlowMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWorkFlow)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockWorkFlow) Stop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockWorkFlowMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWorkFlow)(nil).Stop), arg0)
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// GetSessionOnCreate mocks base method.
func (m *MockSessionManager) GetSessionOnCreate(arg0 string, arg1 bool) (core.Session, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionOnCreate", arg0, arg1)
	ret0, _ := ret[0].(core.Session)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// GetSessionOnCreate indicates an expected call of GetSessionOnCreate.
func (mr *MockSessionManagerMockRecorder) GetSessionOnCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionOnCreate", reflect.TypeOf((*MockSessionManager)(nil).GetSessionOnCreate), arg0, arg1)
}

// StopSession mocks base method.
func (m *MockSessionManager) StopSession(arg0 string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSession", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// StopSession indicates an expected call of StopSession.
func (mr *MockSessionManagerMockRecorder) StopSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSession", reflect.TypeOf((*MockSessionManager)(nil).StopSession), arg0)
}

// MockAgentCore is a mock of AgentCore interface.
type MockAgentCore struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCoreMockRecorder
	isgomock struct{}
}

// MockAgentCoreMockRecorder is the mock recorder for MockAgentCore.
type MockAgentCoreMockRecorder struct {
	mock *MockAgentCore
}

// NewMockAgentCore creates a new mock instance.
func NewMockAgentCore(ctrl *gomock.Controller) *MockAgentCore {
	mock := &MockAgentCore{ctrl: ctrl}
	mock.recorder = &MockAgentCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCore) EXPECT() *MockAgentCoreMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockAgentCore) Acquire() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Acquire indicates an expected call of Acquire.
func (mr *MockAgentCoreMockRecorder) Acquire() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockAgentCore)(nil).Acquire))
}

// BeforeStart mocks base method.
func (m *MockAgentCore) BeforeStart(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStart", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStart indicates an expected call of BeforeStart.
func (mr *MockAgentCoreMockRecorder) BeforeStart(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStart", reflect.TypeOf((*MockAgentCore)(nil).BeforeStart), arg0)
}

// BeforeStop mocks base method.
func (m *MockAgentCore) BeforeStop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStop indicates an expected call of BeforeStop.
func (mr *MockAgentCoreMockRecorder) BeforeStop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStop", reflect.TypeOf((*MockAgentCore)(nil).BeforeStop), arg0)
}

// CloseBenchmarkListeningChannels mocks base method.
func (m *MockAgentCore) CloseBenchmarkListeningChannels() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseBenchmarkListeningChannels")
}

// CloseBenchmarkListeningChannels indicates an expected call of CloseBenchmarkListeningChannels.
func (mr *MockAgentCoreMockRecorder) CloseBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseBenchmarkListeningChannels", reflect.TypeOf((*MockAgentCore)(nil).CloseBenchmarkListeningChannels))
}

// GetBenchmarkListeningChannels mocks base method.
func (m *MockAgentCore) GetBenchmarkListeningChannels() map[string]chan core.StatEvent[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBenchmarkListeningChannels")
	ret0, _ := ret[0].(map[string]chan core.StatEvent[any])
	return ret0
}

// GetBenchmarkListeningChannels indicates an expected call of GetBenchmarkListeningChannels.
func (mr *MockAgentCoreMockRecorder) GetBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBenchmarkListeningChannels", reflect.TypeOf((*MockAgentCore)(nil).GetBenchmarkListeningChannels))
}

// GetConfigPath mocks base method.
func (m *MockAgentCore) GetConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockAgentCoreMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockAgentCore)(nil).GetConfigPath))
}

// GetEventChans mocks base method.
func (m *MockAgentCore) GetEventChans() map[string]chan core.Event[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventChans")
	ret0, _ := ret[0].(map[string]chan core.Event[any])
	return ret0
}

// GetEventChans indicates an expected call of GetEventChans.
func (mr *MockAgentCoreMockRecorder) GetEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventChans", reflect.TypeOf((*MockAgentCore)(nil).GetEventChans))
}

// GetHistory mocks base method.
func (m *MockAgentCore) GetHistory() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockAgentCoreMockRecorder) GetHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockAgentCore)(nil).GetHistory))
}

// GetID mocks base method.
func (m *MockAgentCore) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAgentCoreMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAgentCore)(nil).GetID))
}

// GetKnowledgeBase mocks base method.
func (m *MockAgentCore) GetKnowledgeBase() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockAgentCoreMockRecorder) GetKnowledgeBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockAgentCore)(nil).GetKnowledgeBase))
}

// GetModelProviders mocks base method.
func (m *MockAgentCore) GetModelProviders() []core.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProviders")
	ret0, _ := ret[0].([]core.Provider)
	return ret0
}

// GetModelProviders indicates an expected call of GetModelProviders.
func (mr *MockAgentCoreMockRecorder) GetModelProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProviders", reflect.TypeOf((*MockAgentCore)(nil).GetModelProviders))
}

// GetPrompt mocks base method.
func (m *MockAgentCore) GetPrompt() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockAgentCoreMockRecorder) GetPrompt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockAgentCore)(nil).GetPrompt))
}

// GetSessionConfig mocks base method.
func (m *MockAgentCore) GetSessionConfig() core.SessionConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionConfig")
	ret0, _ := ret[0].(core.SessionConfig)
	return ret0
}

// GetSessionConfig indicates an expected call of GetSessionConfig.
func (mr *MockAgentCoreMockRecorder) GetSessionConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionConfig", reflect.TypeOf((*MockAgentCore)(nil).GetSessionConfig))
}

// GetSessionOnCreate mocks base method.
func (m *MockAgentCore) GetSessionOnCreate(arg0 string, arg1 bool) (core.Session, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionOnCreate", arg0, arg1)
	ret0, _ := ret[0].(core.Session)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// GetSessionOnCreate indicates an expected call of GetSessionOnCreate.
func (mr *MockAgentCoreMockRecorder) GetSessionOnCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionOnCreate", reflect.TypeOf((*MockAgentCore)(nil).GetSessionOnCreate), arg0, arg1)
}

// GetSkills mocks base method.
func (m *MockAgentCore) GetSkills() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkills")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetSkills indicates an expected call of GetSkills.
func (mr *MockAgentCoreMockRecorder) GetSkills() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkills", reflect.TypeOf((*MockAgentCore)(nil).GetSkills))
}

// GetToolsConfig mocks base method.
func (m *MockAgentCore) GetToolsConfig() []core.ToolConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolsConfig")
	ret0, _ := ret[0].([]core.ToolConfig)
	return ret0
}

// GetToolsConfig indicates an expected call of GetToolsConfig.
func (mr *MockAgentCoreMockRecorder) GetToolsConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolsConfig", reflect.TypeOf((*MockAgentCore)(nil).GetToolsConfig))
}

// LoadConfigs mocks base method.
func (m *MockAgentCore) LoadConfigs(path string) (core.AgentCoreConfig, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigs", path)
	ret0, _ := ret[0].(core.AgentCoreConfig)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// LoadConfigs indicates an expected call of LoadConfigs.
func (mr *MockAgentCoreMockRecorder) LoadConfigs(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigs", reflect.TypeOf((*MockAgentCore)(nil).LoadConfigs), path)
}

// OnEvent mocks base method.
func (m *MockAgentCore) OnEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEvent")
}

// OnEvent indicates an expected call of OnEvent.
func (mr *MockAgentCoreMockRecorder) OnEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEvent", reflect.TypeOf((*MockAgentCore)(nil).OnEvent))
}

// RegisterEventChans mocks base method.
func (m *MockAgentCore) RegisterEventChans() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEventChans")
}

// RegisterEventChans indicates an expected call of RegisterEventChans.
func (mr *MockAgentCoreMockRecorder) RegisterEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventChans", reflect.TypeOf((*MockAgentCore)(nil).RegisterEventChans))
}

// Release mocks base method.
func (m *MockAgentCore) Release() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockAgentCoreMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAgentCore)(nil).Release))
}

// SetHistory mocks base method.
func (m *MockAgentCore) SetHistory(arg0 core.HistoryConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockAgentCoreMockRecorder) SetHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockAgentCore)(nil).SetHistory), arg0)
}

// SetID mocks base method.
func (m *MockAgentCore) SetID() *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetID")
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetID indicates an expected call of SetID.
func (mr *MockAgentCoreMockRecorder) SetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockAgentCore)(nil).SetID))
}

// SetKnowledgeBase mocks base method.
func (m *MockAgentCore) SetKnowledgeBase(arg0 core.KnowledgeBaseConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKnowledgeBase", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetKnowledgeBase indicates an expected call of SetKnowledgeBase.
func (mr *MockAgentCoreMockRecorder) SetKnowledgeBase(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKnowledgeBase", reflect.TypeOf((*MockAgentCore)(nil).SetKnowledgeBase), arg0)
}

// SetLanguage mocks base method.
func (m *MockAgentCore) SetLanguage(arg0 core.LanguageType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLanguage", arg0)
}

// SetLanguage indicates an expected call of SetLanguage.
func (mr *MockAgentCoreMockRecorder) SetLanguage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLanguage", reflect.TypeOf((*MockAgentCore)(nil).SetLanguage), arg0)
}

// SetLogger mocks base method.
func (m *MockAgentCore) SetLogger(arg0 core.AgentConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogger", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockAgentCoreMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockAgentCore)(nil).SetLogger), arg0)
}

// SetProviders mocks base method.
func (m *MockAgentCore) SetProviders(arg0 []core.Provider) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviders", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetProviders indicates an expected call of SetProviders.
func (mr *MockAgentCoreMockRecorder) SetProviders(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviders", reflect.TypeOf((*MockAgentCore)(nil).SetProviders), arg0)
}

// SetPrompt mocks base method.
func (m *MockAgentCore) SetPrompt(arg0 core.PromptConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrompt", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetPrompt indicates an expected call of SetPrompt.
func (mr *MockAgentCoreMockRecorder) SetPrompt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrompt", reflect.TypeOf((*MockAgentCore)(nil).SetPrompt), arg0)
}

// SetSkills mocks base method.
func (m *MockAgentCore) SetSkills(arg0 core.SkillConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSkills", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetSkills indicates an expected call of SetSkills.
func (mr *MockAgentCoreMockRecorder) SetSkills(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSkills", reflect.TypeOf((*MockAgentCore)(nil).SetSkills), arg0)
}

// SetToolsConfig mocks base method.
func (m *MockAgentCore) SetToolsConfig(arg0 []core.ToolConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetToolsConfig", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetToolsConfig indicates an expected call of SetToolsConfig.
func (mr *MockAgentCoreMockRecorder) SetToolsConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToolsConfig", reflect.TypeOf((*MockAgentCore)(nil).SetToolsConfig), arg0)
}

// Start mocks base method.
func (m *MockAgentCore) Start(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAgentCoreMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAgentCore)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockAgentCore) Stop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAgentCoreMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAgentCore)(nil).Stop), arg0)
}

// StopSession mocks base method.
func (m *MockAgentCore) StopSession(arg0 string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSession", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// StopSession indicates an expected call of StopSession.
func (mr *MockAgentCoreMockRecorder) StopSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSession", reflect.TypeOf((*MockAgentCore)(nil).StopSession), arg0)
}
