// Code generated by MockGen. DO NOT EDIT.
// Source: core/command.go
//
// Generated by this command:
//
//	mockgen -source=core/command.go -destination=test/mock_command.go -package=test
//

// Package test is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandAccessible is a mock of CommandAccessible interface.
type MockCommandAccessible struct {
	ctrl     *gomock.Controller
	recorder *MockCommandAccessibleMockRecorder
	isgomock struct{}
}

// MockCommandAccessibleMockRecorder is the mock recorder for MockCommandAccessible.
type MockCommandAccessibleMockRecorder struct {
	mock *MockCommandAccessible
}

// NewMockCommandAccessible creates a new mock instance.
func NewMockCommandAccessible(ctrl *gomock.Controller) *MockCommandAccessible {
	mock := &MockCommandAccessible{ctrl: ctrl}
	mock.recorder = &MockCommandAccessibleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandAccessible) EXPECT() *MockCommandAccessibleMockRecorder {
	return m.recorder
}

// GetHelp mocks base method.
func (m *MockCommandAccessible) GetHelp() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelp")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHelp indicates an expected call of GetHelp.
func (mr *MockCommandAccessibleMockRecorder) GetHelp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelp", reflect.TypeOf((*MockCommandAccessible)(nil).GetHelp))
}

// Parse mocks base method.
func (m *MockCommandAccessible) Parse(arg0 string) (any, []core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].([]core.Diagnostic)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockCommandAccessibleMockRecorder) Parse(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockCommandAccessible)(nil).Parse), arg0)
}
