// Code generated by MockGen. DO NOT EDIT.
// Source: core/harness.go
//
// Generated by this command:
//
//	mockgen -source=core/harness.go -destination=test/mock/mock_harness.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockHarness is a mock of Harness interface.
type MockHarness struct {
	ctrl     *gomock.Controller
	recorder *MockHarnessMockRecorder
	isgomock struct{}
}

// MockHarnessMockRecorder is the mock recorder for MockHarness.
type MockHarnessMockRecorder struct {
	mock *MockHarness
}

// NewMockHarness creates a new mock instance.
func NewMockHarness(ctrl *gomock.Controller) *MockHarness {
	mock := &MockHarness{ctrl: ctrl}
	mock.recorder = &MockHarnessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHarness) EXPECT() *MockHarnessMockRecorder {
	return m.recorder
}

// AddAgentHistory mocks base method.
func (m *MockHarness) AddAgentHistory(agentHistory *[]byte, maxSize int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAgentHistory", agentHistory, maxSize)
}

// AddAgentHistory indicates an expected call of AddAgentHistory.
func (mr *MockHarnessMockRecorder) AddAgentHistory(agentHistory, maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentHistory", reflect.TypeOf((*MockHarness)(nil).AddAgentHistory), agentHistory, maxSize)
}

// AddPrompt mocks base method.
func (m *MockHarness) AddPrompt(systemPrompt *[]byte, document []byte, maxSize int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPrompt", systemPrompt, document, maxSize)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AddPrompt indicates an expected call of AddPrompt.
func (mr *MockHarnessMockRecorder) AddPrompt(systemPrompt, document, maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPrompt", reflect.TypeOf((*MockHarness)(nil).AddPrompt), systemPrompt, document, maxSize)
}

// GenerateFinalPrompt mocks base method.
func (m *MockHarness) GenerateFinalPrompt(context core.Context, maxSize int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFinalPrompt", context, maxSize)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateFinalPrompt indicates an expected call of GenerateFinalPrompt.
func (mr *MockHarnessMockRecorder) GenerateFinalPrompt(context, maxSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFinalPrompt", reflect.TypeOf((*MockHarness)(nil).GenerateFinalPrompt), context, maxSize)
}

// GetCurrRoundKnowledges mocks base method.
func (m *MockHarness) GetCurrRoundKnowledges(question core.Question) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrRoundKnowledges", question)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrRoundKnowledges indicates an expected call of GetCurrRoundKnowledges.
func (mr *MockHarnessMockRecorder) GetCurrRoundKnowledges(question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrRoundKnowledges", reflect.TypeOf((*MockHarness)(nil).GetCurrRoundKnowledges), question)
}

// LoadTools mocks base method.
func (m *MockHarness) LoadTools(skillName string, context core.Context, rootPath string) []core.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTools", skillName, context, rootPath)
	ret0, _ := ret[0].([]core.Tool)
	return ret0
}

// LoadTools indicates an expected call of LoadTools.
func (mr *MockHarnessMockRecorder) LoadTools(skillName, context, rootPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTools", reflect.TypeOf((*MockHarness)(nil).LoadTools), skillName, context, rootPath)
}

// SetCurrRoundMessages mocks base method.
func (m *MockHarness) SetCurrRoundMessages(messages *core.Conversation, message core.ReActMessage, windowSize, skip int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCurrRoundMessages", messages, message, windowSize, skip)
}

// SetCurrRoundMessages indicates an expected call of SetCurrRoundMessages.
func (mr *MockHarnessMockRecorder) SetCurrRoundMessages(messages, message, windowSize, skip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrRoundMessages", reflect.TypeOf((*MockHarness)(nil).SetCurrRoundMessages), messages, message, windowSize, skip)
}

// SetFinalQuery mocks base method.
func (m *MockHarness) SetFinalQuery(question *core.Question, knowledge, splitter string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFinalQuery", question, knowledge, splitter)
}

// SetFinalQuery indicates an expected call of SetFinalQuery.
func (mr *MockHarnessMockRecorder) SetFinalQuery(question, knowledge, splitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFinalQuery", reflect.TypeOf((*MockHarness)(nil).SetFinalQuery), question, knowledge, splitter)
}

// SetNextRoundMessages mocks base method.
func (m *MockHarness) SetNextRoundMessages(question *core.Question, messages *core.Conversation) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNextRoundMessages", question, messages)
}

// SetNextRoundMessages indicates an expected call of SetNextRoundMessages.
func (mr *MockHarnessMockRecorder) SetNextRoundMessages(question, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNextRoundMessages", reflect.TypeOf((*MockHarness)(nil).SetNextRoundMessages), question, messages)
}

// auto-add: GetDefaultAnswer mocks base method.
func (m *MockHarness) GetDefaultAnswer() core.Answer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultAnswer")
	ret0, _ := ret[0].(core.Answer)
	return ret0
}

// auto-add: GetDefaultAnswer indicates an expected call of GetDefaultAnswer.
func (mr *MockHarnessMockRecorder) GetDefaultAnswer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultAnswer", reflect.TypeOf((*MockHarness)(nil).GetDefaultAnswer))
}
