// Code generated by MockGen. DO NOT EDIT.
// Source: core/tool.go
//
// Generated by this command:
//
//	mockgen -source=core/tool.go -destination=test/mock_tool.go -package=test
//

// Package test is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockMCPAvailable is a mock of MCPAvailable interface.
type MockMCPAvailable[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockMCPAvailableMockRecorder[T]
	isgomock struct{}
}

// MockMCPAvailableMockRecorder is the mock recorder for MockMCPAvailable.
type MockMCPAvailableMockRecorder[T any] struct {
	mock *MockMCPAvailable[T]
}

// NewMockMCPAvailable creates a new mock instance.
func NewMockMCPAvailable[T any](ctrl *gomock.Controller) *MockMCPAvailable[T] {
	mock := &MockMCPAvailable[T]{ctrl: ctrl}
	mock.recorder = &MockMCPAvailableMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPAvailable[T]) EXPECT() *MockMCPAvailableMockRecorder[T] {
	return m.recorder
}

// Transform mocks base method.
func (m *MockMCPAvailable[T]) Transform(result any) T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transform", result)
	ret0, _ := ret[0].(T)
	return ret0
}

// Transform indicates an expected call of Transform.
func (mr *MockMCPAvailableMockRecorder[T]) Transform(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transform", reflect.TypeOf((*MockMCPAvailable[T])(nil).Transform), result)
}

// MockTool is a mock of Tool interface.
type MockTool struct {
	ctrl     *gomock.Controller
	recorder *MockToolMockRecorder
	isgomock struct{}
}

// MockToolMockRecorder is the mock recorder for MockTool.
type MockToolMockRecorder struct {
	mock *MockTool
}

// NewMockTool creates a new mock instance.
func NewMockTool(ctrl *gomock.Controller) *MockTool {
	mock := &MockTool{ctrl: ctrl}
	mock.recorder = &MockToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTool) EXPECT() *MockToolMockRecorder {
	return m.recorder
}

// GetDescription mocks base method.
func (m *MockTool) GetDescription() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescription")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescription indicates an expected call of GetDescription.
func (mr *MockToolMockRecorder) GetDescription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescription", reflect.TypeOf((*MockTool)(nil).GetDescription))
}

// GetName mocks base method.
func (m *MockTool) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockToolMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockTool)(nil).GetName))
}

// GetRunner mocks base method.
func (m *MockTool) GetRunner() func(map[string]any) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunner")
	ret0, _ := ret[0].(func(map[string]any) *core.Diagnostic)
	return ret0
}

// GetRunner indicates an expected call of GetRunner.
func (mr *MockToolMockRecorder) GetRunner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunner", reflect.TypeOf((*MockTool)(nil).GetRunner))
}

// GetSchema mocks base method.
func (m *MockTool) GetSchema() core.ToolSchema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema")
	ret0, _ := ret[0].(core.ToolSchema)
	return ret0
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockToolMockRecorder) GetSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockTool)(nil).GetSchema))
}

// Validate mocks base method.
func (m *MockTool) Validate(args map[string]any) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", args)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockToolMockRecorder) Validate(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTool)(nil).Validate), args)
}
