// Code generated by MockGen. DO NOT EDIT.
// Source: core/app.go
//
// Generated by this command:
//
//	mockgen -source=core/app.go -destination=test/mock/mock_app.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceProvider is a mock of ServiceProvider interface.
type MockServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockServiceProviderMockRecorder
	isgomock struct{}
}

// MockServiceProviderMockRecorder is the mock recorder for MockServiceProvider.
type MockServiceProviderMockRecorder struct {
	mock *MockServiceProvider
}

// NewMockServiceProvider creates a new mock instance.
func NewMockServiceProvider(ctrl *gomock.Controller) *MockServiceProvider {
	mock := &MockServiceProvider{ctrl: ctrl}
	mock.recorder = &MockServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceProvider) EXPECT() *MockServiceProviderMockRecorder {
	return m.recorder
}

// MockSingalManager is a mock of SingalManager interface.
type MockSingalManager struct {
	ctrl     *gomock.Controller
	recorder *MockSingalManagerMockRecorder
	isgomock struct{}
}

// MockSingalManagerMockRecorder is the mock recorder for MockSingalManager.
type MockSingalManagerMockRecorder struct {
	mock *MockSingalManager
}

// NewMockSingalManager creates a new mock instance.
func NewMockSingalManager(ctrl *gomock.Controller) *MockSingalManager {
	mock := &MockSingalManager{ctrl: ctrl}
	mock.recorder = &MockSingalManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSingalManager) EXPECT() *MockSingalManagerMockRecorder {
	return m.recorder
}

// GracefulQuit mocks base method.
func (m *MockSingalManager) GracefulQuit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulQuit")
}

// GracefulQuit indicates an expected call of GracefulQuit.
func (mr *MockSingalManagerMockRecorder) GracefulQuit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulQuit", reflect.TypeOf((*MockSingalManager)(nil).GracefulQuit))
}

// MockAgentApp is a mock of AgentApp interface.
type MockAgentApp struct {
	ctrl     *gomock.Controller
	recorder *MockAgentAppMockRecorder
	isgomock struct{}
}

// MockAgentAppMockRecorder is the mock recorder for MockAgentApp.
type MockAgentAppMockRecorder struct {
	mock *MockAgentApp
}

// NewMockAgentApp creates a new mock instance.
func NewMockAgentApp(ctrl *gomock.Controller) *MockAgentApp {
	mock := &MockAgentApp{ctrl: ctrl}
	mock.recorder = &MockAgentAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentApp) EXPECT() *MockAgentAppMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockAgentApp) AuthUser(token string) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", token)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockAgentAppMockRecorder) AuthUser(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockAgentApp)(nil).AuthUser), token)
}

// CheckUserPlan mocks base method.
func (m *MockAgentApp) CheckUserPlan(userInfo any, plan core.Plan) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPlan", userInfo, plan)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// CheckUserPlan indicates an expected call of CheckUserPlan.
func (mr *MockAgentAppMockRecorder) CheckUserPlan(userInfo, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPlan", reflect.TypeOf((*MockAgentApp)(nil).CheckUserPlan), userInfo, plan)
}

// GetAgentCore mocks base method.
func (m *MockAgentApp) GetAgentCore() core.AgentCore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentCore")
	ret0, _ := ret[0].(core.AgentCore)
	return ret0
}

// GetAgentCore indicates an expected call of GetAgentCore.
func (mr *MockAgentAppMockRecorder) GetAgentCore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentCore", reflect.TypeOf((*MockAgentApp)(nil).GetAgentCore))
}

// GetAppConfig mocks base method.
func (m *MockAgentApp) GetAppConfig() core.AppConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppConfig")
	ret0, _ := ret[0].(core.AppConfig)
	return ret0
}

// GetAppConfig indicates an expected call of GetAppConfig.
func (mr *MockAgentAppMockRecorder) GetAppConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppConfig", reflect.TypeOf((*MockAgentApp)(nil).GetAppConfig))
}

// GetUserPlan mocks base method.
func (m *MockAgentApp) GetUserPlan(userID string) (core.Plan, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPlan", userID)
	ret0, _ := ret[0].(core.Plan)
	ret1, _ := ret[1].(*core.Diagnostic)
	return ret0, ret1
}

// GetUserPlan indicates an expected call of GetUserPlan.
func (mr *MockAgentAppMockRecorder) GetUserPlan(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPlan", reflect.TypeOf((*MockAgentApp)(nil).GetUserPlan), userID)
}

// GracefulQuit mocks base method.
func (m *MockAgentApp) GracefulQuit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulQuit")
}

// GracefulQuit indicates an expected call of GracefulQuit.
func (mr *MockAgentAppMockRecorder) GracefulQuit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulQuit", reflect.TypeOf((*MockAgentApp)(nil).GracefulQuit))
}

// Render mocks base method.
func (m *MockAgentApp) Render(arg0 core.MessageCode, arg1 core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockAgentAppMockRecorder) Render(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockAgentApp)(nil).Render), arg0, arg1)
}

// RenderSystemMessage mocks base method.
func (m *MockAgentApp) RenderSystemMessage(arg0 *core.DiagnosticList, arg1 core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderSystemMessage", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// RenderSystemMessage indicates an expected call of RenderSystemMessage.
func (mr *MockAgentAppMockRecorder) RenderSystemMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderSystemMessage", reflect.TypeOf((*MockAgentApp)(nil).RenderSystemMessage), arg0, arg1)
}

// SetAgentCore mocks base method.
func (m *MockAgentApp) SetAgentCore(arg0 core.AgentCore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAgentCore", arg0)
}

// SetAgentCore indicates an expected call of SetAgentCore.
func (mr *MockAgentAppMockRecorder) SetAgentCore(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentCore", reflect.TypeOf((*MockAgentApp)(nil).SetAgentCore), arg0)
}

// SetAppConfig mocks base method.
func (m *MockAgentApp) SetAppConfig(arg0 core.AppConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAppConfig", arg0)
}

// SetAppConfig indicates an expected call of SetAppConfig.
func (mr *MockAgentAppMockRecorder) SetAppConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAppConfig", reflect.TypeOf((*MockAgentApp)(nil).SetAppConfig), arg0)
}

// SetRouter mocks base method.
func (m *MockAgentApp) SetRouter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRouter")
}

// SetRouter indicates an expected call of SetRouter.
func (mr *MockAgentAppMockRecorder) SetRouter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRouter", reflect.TypeOf((*MockAgentApp)(nil).SetRouter))
}

// Start mocks base method.
func (m *MockAgentApp) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockAgentAppMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAgentApp)(nil).Start))
}

// Stop mocks base method.
func (m *MockAgentApp) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockAgentAppMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAgentApp)(nil).Stop))
}

// Translate mocks base method.
func (m *MockAgentApp) Translate(key core.MessageCode, targetLanguage core.LanguageType) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", key, targetLanguage)
	ret0, _ := ret[0].(string)
	return ret0
}

// Translate indicates an expected call of Translate.
func (mr *MockAgentAppMockRecorder) Translate(key, targetLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockAgentApp)(nil).Translate), key, targetLanguage)
}

// Welcome mocks base method.
func (m *MockAgentApp) Welcome() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Welcome")
	ret0, _ := ret[0].(string)
	return ret0
}

// Welcome indicates an expected call of Welcome.
func (mr *MockAgentAppMockRecorder) Welcome() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Welcome", reflect.TypeOf((*MockAgentApp)(nil).Welcome))
}
