// Code generated by MockGen. DO NOT EDIT.
// Source: core/tool.go
//
// Generated by this command:
//
//	mockgen -source=core/tool.go -destination=test/mock/mock_tool.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockSkill is a mock of Skill interface.
type MockSkill struct {
	ctrl     *gomock.Controller
	recorder *MockSkillMockRecorder
	isgomock struct{}
}

// MockSkillMockRecorder is the mock recorder for MockSkill.
type MockSkillMockRecorder struct {
	mock *MockSkill
}

// NewMockSkill creates a new mock instance.
func NewMockSkill(ctrl *gomock.Controller) *MockSkill {
	mock := &MockSkill{ctrl: ctrl}
	mock.recorder = &MockSkillMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkill) EXPECT() *MockSkillMockRecorder {
	return m.recorder
}

// GetDescription mocks base method.
func (m *MockSkill) GetDescription() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescription")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescription indicates an expected call of GetDescription.
func (mr *MockSkillMockRecorder) GetDescription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescription", reflect.TypeOf((*MockSkill)(nil).GetDescription))
}

// GetName mocks base method.
func (m *MockSkill) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockSkillMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockSkill)(nil).GetName))
}

// GetTools mocks base method.
func (m *MockSkill) GetTools() []core.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTools")
	ret0, _ := ret[0].([]core.Tool)
	return ret0
}

// GetTools indicates an expected call of GetTools.
func (mr *MockSkillMockRecorder) GetTools() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTools", reflect.TypeOf((*MockSkill)(nil).GetTools))
}

// MockTool is a mock of Tool interface.
type MockTool struct {
	ctrl     *gomock.Controller
	recorder *MockToolMockRecorder
	isgomock struct{}
}

// MockToolMockRecorder is the mock recorder for MockTool.
type MockToolMockRecorder struct {
	mock *MockTool
}

// NewMockTool creates a new mock instance.
func NewMockTool(ctrl *gomock.Controller) *MockTool {
	mock := &MockTool{ctrl: ctrl}
	mock.recorder = &MockToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTool) EXPECT() *MockToolMockRecorder {
	return m.recorder
}

// GetContext mocks base method.
func (m *MockTool) GetContext() core.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext")
	ret0, _ := ret[0].(core.Context)
	return ret0
}

// GetContext indicates an expected call of GetContext.
func (mr *MockToolMockRecorder) GetContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockTool)(nil).GetContext))
}

// GetDescription mocks base method.
func (m *MockTool) GetDescription() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescription")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescription indicates an expected call of GetDescription.
func (mr *MockToolMockRecorder) GetDescription() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescription", reflect.TypeOf((*MockTool)(nil).GetDescription))
}

// GetName mocks base method.
func (m *MockTool) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockToolMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockTool)(nil).GetName))
}

// GetRunner mocks base method.
func (m *MockTool) GetRunner() func(map[string]any) (string, *core.Diagnostic) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunner")
	ret0, _ := ret[0].(func(map[string]any) (string, *core.Diagnostic))
	return ret0
}

// GetRunner indicates an expected call of GetRunner.
func (mr *MockToolMockRecorder) GetRunner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunner", reflect.TypeOf((*MockTool)(nil).GetRunner))
}

// GetSandboxEnv mocks base method.
func (m *MockTool) GetSandboxEnv() core.SandboxSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSandboxEnv")
	ret0, _ := ret[0].(core.SandboxSpec)
	return ret0
}

// GetSandboxEnv indicates an expected call of GetSandboxEnv.
func (mr *MockToolMockRecorder) GetSandboxEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSandboxEnv", reflect.TypeOf((*MockTool)(nil).GetSandboxEnv))
}

// GetSchema mocks base method.
func (m *MockTool) GetSchema() core.ToolSchema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema")
	ret0, _ := ret[0].(core.ToolSchema)
	return ret0
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockToolMockRecorder) GetSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockTool)(nil).GetSchema))
}

// IsDestructive mocks base method.
func (m *MockTool) IsDestructive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDestructive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDestructive indicates an expected call of IsDestructive.
func (mr *MockToolMockRecorder) IsDestructive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDestructive", reflect.TypeOf((*MockTool)(nil).IsDestructive))
}

// ToShellScript mocks base method.
func (m *MockTool) ToShellScript(args map[string]any) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToShellScript", args)
	ret0, _ := ret[0].(string)
	return ret0
}

// ToShellScript indicates an expected call of ToShellScript.
func (mr *MockToolMockRecorder) ToShellScript(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToShellScript", reflect.TypeOf((*MockTool)(nil).ToShellScript), args)
}

// Validate mocks base method.
func (m *MockTool) Validate(args map[string]any) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", args)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockToolMockRecorder) Validate(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTool)(nil).Validate), args)
}
