// Code generated by MockGen. DO NOT EDIT.
// Source: core/session.go
//
// Generated by this command:
//
//	mockgen -source=core/session.go -destination=test/mock/mock_session.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	core "github.com/David3310273/go-agent/core"
	gomock "go.uber.org/mock/gomock"
)

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// BeforeStart mocks base method.
func (m *MockSession) BeforeStart(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStart", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStart indicates an expected call of BeforeStart.
func (mr *MockSessionMockRecorder) BeforeStart(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStart", reflect.TypeOf((*MockSession)(nil).BeforeStart), arg0)
}

// BeforeStop mocks base method.
func (m *MockSession) BeforeStop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeStop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// BeforeStop indicates an expected call of BeforeStop.
func (mr *MockSessionMockRecorder) BeforeStop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeStop", reflect.TypeOf((*MockSession)(nil).BeforeStop), arg0)
}

// CloseBenchmarkListeningChannels mocks base method.
func (m *MockSession) CloseBenchmarkListeningChannels() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseBenchmarkListeningChannels")
}

// CloseBenchmarkListeningChannels indicates an expected call of CloseBenchmarkListeningChannels.
func (mr *MockSessionMockRecorder) CloseBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseBenchmarkListeningChannels", reflect.TypeOf((*MockSession)(nil).CloseBenchmarkListeningChannels))
}

// GenerateFinalContext mocks base method.
func (m *MockSession) GenerateFinalContext(query core.Question) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFinalContext", query)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateFinalContext indicates an expected call of GenerateFinalContext.
func (mr *MockSessionMockRecorder) GenerateFinalContext(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFinalContext", reflect.TypeOf((*MockSession)(nil).GenerateFinalContext), query)
}

// GetBenchmarkListeningChannels mocks base method.
func (m *MockSession) GetBenchmarkListeningChannels() map[string]chan core.StatEvent[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBenchmarkListeningChannels")
	ret0, _ := ret[0].(map[string]chan core.StatEvent[any])
	return ret0
}

// GetBenchmarkListeningChannels indicates an expected call of GetBenchmarkListeningChannels.
func (mr *MockSessionMockRecorder) GetBenchmarkListeningChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBenchmarkListeningChannels", reflect.TypeOf((*MockSession)(nil).GetBenchmarkListeningChannels))
}

// GetConfigs mocks base method.
func (m *MockSession) GetConfigs() core.SessionConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigs")
	ret0, _ := ret[0].(core.SessionConfig)
	return ret0
}

// GetConfigs indicates an expected call of GetConfigs.
func (mr *MockSessionMockRecorder) GetConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigs", reflect.TypeOf((*MockSession)(nil).GetConfigs))
}

// GetConversation mocks base method.
func (m *MockSession) GetConversation() *core.Conversation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversation")
	ret0, _ := ret[0].(*core.Conversation)
	return ret0
}

// GetConversation indicates an expected call of GetConversation.
func (mr *MockSessionMockRecorder) GetConversation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversation", reflect.TypeOf((*MockSession)(nil).GetConversation))
}

// GetEventChans mocks base method.
func (m *MockSession) GetEventChans() map[string]chan core.Event[any] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventChans")
	ret0, _ := ret[0].(map[string]chan core.Event[any])
	return ret0
}

// GetEventChans indicates an expected call of GetEventChans.
func (mr *MockSessionMockRecorder) GetEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventChans", reflect.TypeOf((*MockSession)(nil).GetEventChans))
}

// GetID mocks base method.
func (m *MockSession) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockSessionMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockSession)(nil).GetID))
}

// GetModelProviders mocks base method.
func (m *MockSession) GetModelProviders() []core.Provider {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelProviders")
	ret0, _ := ret[0].([]core.Provider)
	return ret0
}

// GetModelProviders indicates an expected call of GetModelProviders.
func (mr *MockSessionMockRecorder) GetModelProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelProviders", reflect.TypeOf((*MockSession)(nil).GetModelProviders))
}

// GetQuestionChan mocks base method.
func (m *MockSession) GetQuestionChan() chan core.Question {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionChan")
	ret0, _ := ret[0].(chan core.Question)
	return ret0
}

// GetQuestionChan indicates an expected call of GetQuestionChan.
func (mr *MockSessionMockRecorder) GetQuestionChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionChan", reflect.TypeOf((*MockSession)(nil).GetQuestionChan))
}

// GetStatus mocks base method.
func (m *MockSession) GetStatus() core.SessionStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(core.SessionStatus)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockSessionMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockSession)(nil).GetStatus))
}

// NewSubSession mocks base method.
func (m *MockSession) NewSubSession() core.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSubSession")
	ret0, _ := ret[0].(core.Session)
	return ret0
}

// NewSubSession indicates an expected call of NewSubSession.
func (mr *MockSessionMockRecorder) NewSubSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSubSession", reflect.TypeOf((*MockSession)(nil).NewSubSession))
}

// OnEvent mocks base method.
func (m *MockSession) OnEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnEvent")
}

// OnEvent indicates an expected call of OnEvent.
func (mr *MockSessionMockRecorder) OnEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnEvent", reflect.TypeOf((*MockSession)(nil).OnEvent))
}

// ProcessQuery mocks base method.
func (m *MockSession) ProcessQuery(query core.Question) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessQuery", query)
}

// ProcessQuery indicates an expected call of ProcessQuery.
func (mr *MockSessionMockRecorder) ProcessQuery(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessQuery", reflect.TypeOf((*MockSession)(nil).ProcessQuery), query)
}

// RegisterEventChans mocks base method.
func (m *MockSession) RegisterEventChans() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEventChans")
}

// RegisterEventChans indicates an expected call of RegisterEventChans.
func (mr *MockSessionMockRecorder) RegisterEventChans() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventChans", reflect.TypeOf((*MockSession)(nil).RegisterEventChans))
}

// SaveHistory mocks base method.
func (m *MockSession) SaveHistory(arg0 core.Conversation) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHistory", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SaveHistory indicates an expected call of SaveHistory.
func (mr *MockSessionMockRecorder) SaveHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHistory", reflect.TypeOf((*MockSession)(nil).SaveHistory), arg0)
}

// SelectLocalKB mocks base method.
func (m *MockSession) SelectLocalKB(arg0 core.Question) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectLocalKB", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// SelectLocalKB indicates an expected call of SelectLocalKB.
func (mr *MockSessionMockRecorder) SelectLocalKB(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectLocalKB", reflect.TypeOf((*MockSession)(nil).SelectLocalKB), arg0)
}

// SelectTools mocks base method.
func (m *MockSession) SelectTools(arg0 core.Question, arg1 core.ReActMessage) []core.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectTools", arg0, arg1)
	ret0, _ := ret[0].([]core.Tool)
	return ret0
}

// SelectTools indicates an expected call of SelectTools.
func (mr *MockSessionMockRecorder) SelectTools(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectTools", reflect.TypeOf((*MockSession)(nil).SelectTools), arg0, arg1)
}

// SetLogger mocks base method.
func (m *MockSession) SetLogger(arg0 core.SessionConfig) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogger", arg0)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockSessionMockRecorder) SetLogger(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockSession)(nil).SetLogger), arg0)
}

// SetStatus mocks base method.
func (m *MockSession) SetStatus(status core.SessionStatus) *core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", status)
	ret0, _ := ret[0].(*core.Diagnostic)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockSessionMockRecorder) SetStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockSession)(nil).SetStatus), status)
}

// Start mocks base method.
func (m *MockSession) Start(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSessionMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSession)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockSession) Stop(arg0 core.AgentCoreConfig) []core.Diagnostic {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].([]core.Diagnostic)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSessionMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSession)(nil).Stop), arg0)
}

// MockSessionAnswer is a mock of SessionAnswer interface.
type MockSessionAnswer struct {
	ctrl     *gomock.Controller
	recorder *MockSessionAnswerMockRecorder
	isgomock struct{}
}

// MockSessionAnswerMockRecorder is the mock recorder for MockSessionAnswer.
type MockSessionAnswerMockRecorder struct {
	mock *MockSessionAnswer
}

// NewMockSessionAnswer creates a new mock instance.
func NewMockSessionAnswer(ctrl *gomock.Controller) *MockSessionAnswer {
	mock := &MockSessionAnswer{ctrl: ctrl}
	mock.recorder = &MockSessionAnswerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionAnswer) EXPECT() *MockSessionAnswerMockRecorder {
	return m.recorder
}

// GetSessionID mocks base method.
func (m *MockSessionAnswer) GetSessionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSessionID indicates an expected call of GetSessionID.
func (mr *MockSessionAnswerMockRecorder) GetSessionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionID", reflect.TypeOf((*MockSessionAnswer)(nil).GetSessionID))
}

// ToString mocks base method.
func (m *MockSessionAnswer) ToString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToString")
	ret0, _ := ret[0].(string)
	return ret0
}

// ToString indicates an expected call of ToString.
func (mr *MockSessionAnswerMockRecorder) ToString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToString", reflect.TypeOf((*MockSessionAnswer)(nil).ToString))
}
